### ISSUE TITLE
建议使用微软雅黑作为界面的字体

### ISSUE THREAD

**Issue by Youxikong** [422658476/MPV-EASY-Player#10]
默认的宋体在低分屏上渲染非常糟糕，使用微软雅黑作为界面字体会有更加好的效果。

**Comment by 422658476** [comment]
宋体是一种点阵字体，这种字体在低分辨率的显示屏上最大的好处就是清晰和锐利。
微软雅黑是一种矢量字体，这种字体在文字较大时才有较好的清晰度。
无边框模式下，osc使用的是9号的宋体，菜单则是使用的微软雅黑。
mpv原生gui下，osc使用的是字体相近（约9号）的微软雅黑，你可以自己比较2者的清晰度。
如果你显示屏上的宋体渲染非常糟糕，那么很有可能是除字体之外的因素造成的，比如dpi

**Comment by Youxikong** [comment]
@422658476 我的电脑屏幕是1080P。使用默认的宋体，文字全部糊成一团。而使用fontmod把字体改为微软雅黑就非常清晰锐利了。
实际体验，字体越小，反而微软雅黑更加清晰。
需要截图对比吗？

**Comment by 422658476** [comment]
当然需要截图，因为宋体显示是否锐利，你只要从
https://github.com/422658476/MPV-EASY-Player
的截图上就可以看出来，点阵字体是对应像素点的，这就是为什么低分辨率上和小字体时清晰的原因。
矢量字体则是会渲染一些阴影，越是小，越是字体模糊。

**Comment by Youxikong** [comment]
> 当然需要截图，因为宋体显示是否锐利，你只要从
> https://github.com/422658476/MPV-EASY-Player
> 的截图上就可以看出来，点阵字体是对应像素点的，这就是为什么低分辨率上和小字体时清晰的原因。
> 矢量字体则是会渲染一些阴影，越是小，越是字体模糊。

![image](https://user-images.githubusercontent.com/26603498/72886713-4487a700-3d45-11ea-8f3b-8234252e276f.png)

修改UI字体为微软雅黑。

![image](https://user-images.githubusercontent.com/26603498/72886767-608b4880-3d45-11ea-98fe-389846d7bce0.png)

默认UI字体宋体。

**Comment by 422658476** [comment]
你的显示器显示的字体一点问题都没有，你的截图和我的截图上显示的一模一样。
我不清楚你对糊成一团是如何理解的。
就像我描述的那样，点阵的宋体是最为锐利和清晰的，因为显示的每个像素点和字体上笔画都是对应的。
而你修改成微软雅黑后，可以看到字体是明显没有宋体锐利的，这也是微软雅黑和矢量字体的特色，矢量字体的不清晰和笔画周围稍微的模糊可以放松眼睛，但在字体较小的情况下，这反而是反效果。
你可以从 文字 800x480 最后一个0字作为比较，宋体渲染0这个字的上下左右都只用单行像素，而微软雅黑渲染0的左右2测都需要2竖行像素，就是为了渲染所谓的圆润效果，一行为主体，一行为较淡的轮廓，这个轮廓才是大家描述的糊，而使用单行像素渲染的字体不管怎么渲染它都是不会有一点模糊的。

**Comment by Youxikong** [comment]
@422658476 我有近视，离开屏幕一段距离，宋体已经彻底糊掉了，微软雅黑还是非常清晰的。

**Comment by 422658476** [comment]
这个。。。。不可能为了让你看的清晰，强制其他看的清楚的人看不清楚吧？毕竟看的清楚的是绝大部分人。
宋体和微软雅黑是否清晰，这个问题其实是无需讨论的，因为这是公认的，这个公认的依据也是基于它们不同的显示方式、渲染原理和不同的使用环境获得的。
你如果看宋体糊掉，但是微软雅黑反而清晰，这更是无法理解的。
因为当宋体糊掉时，你已经把一个像素看成2个像素了，而微软雅黑应该已经从2个像素变为4个像素，应该更糊。

**Comment by Youxikong** [comment]
@422658476 好吧，还是非常谢谢你的无偿贡献。
