### ISSUE TITLE
[問題] Lua脚本在Linux上出現異常

### ISSUE THREAD

**Issue by morristai** [422658476/MPV-EASY-Player#12]
感謝詳細的教程，這裡遇到一個小問題。
這是我用原生MPV Player照步驟改主題的結果。
環境：Ubuntu 19.10 with GNOME 3.34.3 
![Screenshot from 2020-03-31 05-38-22](https://user-images.githubusercontent.com/10728152/77965197-1a3d0180-7313-11ea-9212-5526950c44d2.png)
然而MPV Player雖然有改變主題，但是貌似不是lua script所描述的樣子，舉例iina的這個script所呈現的：
![Screenshot from 2020-03-31 05-46-19](https://user-images.githubusercontent.com/10728152/77965141-faa5d900-7312-11ea-844b-95477058a116.png)

請教一下是哪裡出了問題？Thanks.

**Comment by 422658476** [comment]
首先移除osc.lua，并在mpv.conf中添加osc=no这一行，让mpv隐藏内置的osc。
运行mpv，如果看到osc看不见了，说明osc=no生效了，这样内置osc被隐藏后就不会对你添加的osc.lua造成干扰。
然后，添加osc.lua,运行mpv，mpv中如果出现osc，那么说明你添加的osc.lua已经生效。
接下来：
理论上，osc.lua跨平台通用，但实际上，在每个平台上使用是会有所差异，比如在mac平台上，mpv 0.32对于layout=box就完全不支持。
所以如果你的osc.lua在windows下显示没有问题，但是在ubuntu下变成这种默认模式，那么可以调整osc.conf中其他参数的值来检测mpv for linux对osc的支持情况。
比如调整osc.conf中boxalpha的值从0到255，如果osc的透明度有变化，那么说明mpv for linux对于这个参数是支持的，也可以证明对于osc.conf的读取也没有问题。
那么接下来就可以调整osc.conf中layout=***这个参数，layout的可选值有：box, slimbox, bottombar, topbar.
修改后的样式在layout=box时才会正常显示。
如果layout=bottombar时，mpv中osc的样式没有变成bottombar样式，那么说明mpv for linux对于layout这个参数可能支持性不好或者不支持。

**Comment by morristai** [comment]
Ubuntu在mpv.conf中添加osc=no之後osc就消失了，添加osc.lua也是一樣，之後在Windows上試試好了。感謝
