### ISSUE TITLE
大佬能不能单独做一个右键菜单，实现一些基本功能

### ISSUE THREAD

**Issue by chwt163** [422658476/MPV-EASY-Player#14]
一个脚本实现打开文件、退出程序之类的。

**Comment by 422658476** [comment]
你要的功能不都在右上角菜单中，系统托盘菜单中吗？

**Comment by chwt163** [comment]
> 你要的功能不都在右上角菜单中，系统托盘菜单中吗？

现在这个菜单对我来讲还是太多了。。。我是想搞得再简洁一点，又不太喜欢快捷键。
