### ISSUE TITLE
请问 osc.lua 是怎么定义移动鼠标显示 osc 的？

### ISSUE THREAD

**Issue by chwt163** [422658476/MPV-EASY-Player#15]
提取 MPV-EASY-Player 的 osc.lua，根据这个教程：
https://www.rjno1.com/modify-mpv-osc-style/
我自己更改了一下，只保留了“播放暂停，已播放时间，进度条，总时间，音量，全屏”这几个元素单行显示，觉得效果不错。非常感谢作者。

就是有一个问题，原版的 OSC 是只要鼠标有移动，OSC 就会显示出来，MPV-EASY-Player 的 osc.lua 是需要把鼠标在接近上下边框的地方进行移动才会显示 OSC，在视频中间移动是不显示的，我想改成原版那种，不知道要改哪些地方？

还有就是 OSC 标题的字体大小是再哪里定义的呢？想把字体改大一点。

**Comment by 422658476** [comment]
MpvEasySettings.exe-osc-鼠标在多大区域移动能激活osc（mpv的说明文档中有描述）
字体大小：
osc.lua 中顶部local osc_styles =部分可以调整字体。
请网上查阅字幕是如何调整文字大小等格式的，osc中的控制部分完全使用字幕的方式调整外观
