### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by noxsave** [422658476/MPV-EASY-Player#16]
感谢作者，以下是我在使用过程中想到的一些建议，还望采纳：
1.希望无边GUI模式下，可以调整底部进度条样式；
2.希望可以有“卸载”相关的选项，例如清除“文件关联信息”等；
3.快捷键提示里可以加入更多常用的说明，例如逐帧播放，截图等功能的快捷键；
4.希望能有选项可以更改截图的默认存放位置。

最后再次感谢作者，mpv对于小白来说设置过于复杂，mpv-easy-player在一定程度上改善了小白用户的使用体验，希望作者能继续加油，期待有一天GUI界面能成长到有如mpc-hc一样的体验。

**Comment by 422658476** [comment]
1、无边GUI模式下，底部进度条样式暂时不考虑增加，因为这个涉及到很多外观和进度有关的精密计算，不过下个版本会提供更多样式的无边GUI模式osc。
2、这个播放器不需要卸载，因为它是一个绿色软件，和系统有关联的仅有c盘的一个快捷方式和文件关联有关的注册表，如果你不使用文件关联，那么连注册表信息都没有。如果你要清除文件关联信息：
a、只需要点击【设置默认程序】，在里面弃选即可。
b、或者使用其他视频播放器的关联功能。
c、或者重命名mpv-easy player所在文件夹的名字，然后用ccleaner一类的软件清理一遍注册表即可。
3、和截图、逐帧播放、截图的默认存放位置等有关的快捷键说明和选项不会被添加。
这些都是不常用的功能，截图、逐帧播放的快捷键可以在input.conf或者mpv-easy player所在文件夹\mpv\doc\mpbindings.png中找到，截图的存放位置请自行查阅说明文档：
https://mpv.io/manual/stable/#options-screenshot-directory
