### ISSUE TITLE
MPV-EASY-Player能否通过命令调动？

### ISSUE THREAD

**Issue by Sailing168** [422658476/MPV-EASY-Player#17]
MPV-EASY-Player能否制作成单文件？想通过命令直接调动MPV-EASY-Player，但实际上无法调动。单文件也无法调动

**Comment by 422658476** [comment]
mpv是命令行播放器，mpv-easy player是它的gui前端，如果你想要命令调用，请直接查看mpv的使用手册，直接调用mpv
