### ISSUE TITLE
如何取消文件关联呢

### ISSUE THREAD

**Issue by NoahELE** [422658476/MPV-EASY-Player#19]
关联之后会一直在右键菜单打开方式里，能像mpv一样提供一个uninstall.bat来解除关联吗？

**Comment by 422658476** [comment]
第一种：直接把mpv-easy player的文件夹重命名成其他名字，然后使用ccleaner清理一遍注册表即可，之后再把文件夹重命名回来。
第二种：尝试在关联文件界面取消勾选或者选择其他播放器。
第三种：使用其他视频播放器关联同类文件。
如果只是想要清除右键菜单，请使用第一种
