### ISSUE TITLE
Italian update:

### ISSUE THREAD

**Issue by 422658476** [422658476/MPV-EASY-Player#33]
@bovirus

Hello bovirus, in the next version, the setting interface needs to add a [gradient color progress bar] option, if the Italian translation of this option is [Barra di avanzamento del gradiente di colore], then I will directly modify the Italian file and upload it , If the translation is wrong, please tell me the correct translation.
Many thanks.

**Comment by bovirus** [comment]
@422658476 

ENG - [gradient color progress bar] 

ITA - [barr progresso gradiente colore]

Thanks.

**Comment by 422658476** [comment]
Okay, I have completed the update of the language file and uploaded it. This is the preview after completion. Thank you very much.

I will close this issue. 

![111111](https://user-images.githubusercontent.com/37802190/140899785-dcdef9b4-4a7f-4871-81ff-702dc38d95ae.png)
.
