### ISSUE TITLE
问一下如何在osc样式中正确显示详细信息？

### ISSUE THREAD

**Issue by Djangoogle** [422658476/MPV-EASY-Player#34]
我使用的是原生mpv，没有用MPV-EASY-Player
添加了最新的osc.lua和osc.conf，但是始终调试不出下图中osc的样式
![](https://raw.githubusercontent.com/422658476/MPV-EASY-Player/master/img/mpv-easy-player-osc-lua.jpg)
即：音量:100% 硬解:d3d11va 置顶:no 音轨: (1) 字幕:no 分辨率:1920x1080 声道……这种效果
请问要怎么配置呢，是不是必须要用MPV-EASY-Player才可以正确显示这种osc样式？

**Comment by 422658476** [comment]
osc.conf中添加下面这行，这行因为太复杂太容易错是直接传输给mpv的，默认没有写在文件中。

title=音量:${volume}%  硬解:${hwdec-current}  置顶:${ontop}  音轨:${audio}  字幕:${sub}  文件分辨率:${width}x${height}  声道:${audio-params/hr-channels}  帧数:${container-fps}

通过查看mpv的说明文档你还可以添加其他的，但请注意不要添加太多，添加太多会超出osc右侧边界，没有问题请关闭这个issue，万分感谢

**Comment by Djangoogle** [comment]
thx veeeeeeeeeeeeeeeeeeeeeeery much
