### ISSUE TITLE
能增加一个类似B站的播放界面吗？

### ISSUE THREAD

**Issue by chwt163** [422658476/MPV-EASY-Player#35]
简洁一点就好，最好是 mpv 原生 gui
![无标题](https://user-images.githubusercontent.com/70951194/145955044-79d2ba1a-8661-43cc-b30b-49d3fd022d77.png)

**Comment by 422658476** [comment]
使用mpv-easy无边框gui【mpv 原生 gui请自行制作】
设置 - osc - osc样式 - 选择【webplayer】

没有问题请关闭这个issue，万分感谢
