### ISSUE TITLE
Italian update:

### ISSUE THREAD

**Issue by 422658476** [422658476/MPV-EASY-Player#36]
![border-radius](https://user-images.githubusercontent.com/37802190/146233656-c37661c8-3dcb-4d67-857d-0aa38e8ec475.png)

@bovirus

Hello, bovirus.
In the next version, I need to add a setting called [Interface radius size:]. If you don’t know the meaning of the text, you can refer to the picture. Basically, the interface becomes the rounded corner style of windows 11. This setting is used to: change the interface circle The size of the angle.
If possible, please give me the correct English and Italian translations, thank you very much. 

zh-CN     界面半径大小:
en-US     Interface radius size:

**Comment by bovirus** [comment]
@422658476 

en-US Interface radius size:
it-IT Dimensione raggio interfaccia:

Thanks.

**Comment by 422658476** [comment]
Thank you very much, the reply is so fast.
I have uploaded the latest language file.
The picture is a preview.
I will close this issue.
Many thanks. 
![1111](https://user-images.githubusercontent.com/37802190/146256109-99f99443-3b64-46c0-a9ca-f9764af6fca2.png)
