### ISSUE TITLE
请问如何锁定纵横比？

### ISSUE THREAD

**Issue by AliSwitch** [422658476/MPV-EASY-Player#38]
调节窗口大小时，视频大小同步改变（不会出现黑边）
直接用MPV打开视频时，默认就是这样的，但是EASY Player却不行

**Comment by 422658476** [comment]
锁定纵横比会严重影响到窗口调整的灵活性。
1、当启用左右裁切时，锁定纵横比反而会产生无法调节到想要窗口宽高比的情形。
2、当不锁定纵横比时，可以给与用户更多的选择：osc显示在视频区域，或者osc显示在黑边中。
3、当不锁定纵横比时，自动带有：手动维持视频纵横比、窗口使用自定纵横比2种功能。
如果是因为调节窗口尺寸后想要恢复到最初的视频纵横比，请点击osc中的 【宽度x高度】，会自动帮你恢复到默认的窗口样式。
没有问题请关闭这个issue，万分感谢

**Comment by AliSwitch** [comment]
> 点击osc中的 【宽度x高度】

这个是指哪个位置？没有找到

**Comment by 422658476** [comment]
![截屏2022-01-24 16 19 57](https://user-images.githubusercontent.com/37802190/150747775-dbd9e368-8354-4742-9745-ee4c682f7b05.png)

**Comment by AliSwitch** [comment]
> 

好的，非常感谢
