### ISSUE TITLE
Italian update and English correction 

### ISSUE THREAD

**Issue by 422658476** [422658476/MPV-EASY-Player#40]
@bovirus

Hello, bovirus.
I need to add multiple functions in the next version. Now the functions are basically completed, and only multi-language support is left (there may be minor changes in the future). Since these functions have a lot of interface changes, they need to be translated. There will be a lot of text, I have put them below and I have attached them in English, please translate them into Italian if you can, and if there are mistakes in the English translation, please help me to correct it, thanks a lot, it may cost you A lot of energy and time, sorry for that.
I'll upload the language file and give you a preview screenshot when it's over. 

---

菜单
Menu

---

调节范围:5%-100%
基于可用桌面区域计算.
注意:
不支持以像素作为计量单位.
最小宽度:640px.
adjustment range: 5%-100%
calculated based on available desktop area.
notice:
pixels are not supported as units of measurement.
minimum width: 640px.

---

初始窗口最大尺寸(宽度x高度)*:
initial window max size (width x height)*:

---

进度条拖动时实时更新进度
real-time update progress when the progress bar is dragged

---

菜单(1)
Menu(1)

---

显示自定义菜单A
show custom menu A

---

自定义菜单A的名字:
name of custom menu A:

---

上移
move up

---

下移
move down

---

菜单项名字
menu item name 

---

用法*
Usage*

---

数据文件存放路径:data\mpv-easy-data\menu.conf

使用菜单项替代键盘发送一组快捷键给mpv.
一组快捷键中的每个快捷键会间隔一小段时间分别发送.
一组快捷键中使用空格区分每个快捷键.

注意:
执行过程中请勿触发鼠标和键盘.

请使用input.conf中的快捷键表示方式,比如:
回车=enter
空格=space

适用于:
1.不想要记忆快捷键.
2.依次按下多个快捷键才能完成的事项.
3.在mpv的命令行窗口自动执行某些命令.

例子:

菜单项名字:
This is the name of a menu item
快捷键:
ctrl+a alt+b shift+c ctrl+shift+d

按下【This is the name of a menu item】菜单项后发送:
ctrl+a
等待几百毫秒
alt+b
等待几百毫秒
shift+c
等待几百毫秒
ctrl+shift+d

例子:

快捷键:
` s e t space v o l u m e space 8 8 enter esc

打开命令行窗口
输入并执行set volume 88
退出命令行窗口

注意:
MPV原生GUI模式下,如果启用多实例
1.执行过程中请勿切换窗口
2.建议关闭置顶功能.
data file storage path: data\mpv-easy-data\menu.conf

use a menu item instead of the keyboard to send a set of shortcuts to mpv.
each shortcut key in a set of shortcut keys is sent separately at a short interval.
a space is used to separate each shortcut key in a set of shortcut keys.

notice:
do not trigger mouse and keyboard during execution.

please use the shortcut key representation in input.conf, for example:
enter=enter
space=space

applies to:
1. don't want to memorize shortcut keys.
2. things that can be completed by pressing multiple shortcut keys in turn.
3. automatically execute certain commands in the command line window of mpv.

example:

menu item name:
this is the name of a menu item
hot key:
ctrl+a alt+b shift+c ctrl+shift+d

send after pressing the [this is the name of a menu item] menu item:
ctrl+a
wait a few hundred milliseconds
alt+b
wait a few hundred milliseconds
shift+c
wait a few hundred milliseconds
ctrl+shift+d

example:

hot key:
` s e t space v o l u m e space 8 8 enter esc

open a command line window
enter and execute set volume 88
exit the command line window

notice:
in mpv native gui mode, if multiple instances are enabled
1. do not switch windows during execution
2. it is recommended to turn off the sticky top function.

**Comment by 422658476** [comment]
hello bovirus:
Your email is folded by default in github, I almost didn't understand it.
Thank you very much, the reply is really fast.
I found that one of the lines may have been left out, so it doesn't seem to have been translated.
This sentence is below ======<<<<<==== 

Google's translation into Italian is the following line, if there is any problem with this translation, I need your confirmation, thank you very much. 

percorso di archiviazione del file di dati: data\mpv-easy-data\menu.conf

rest with =========<<<<============
It's a translation error, because these messages are sent to mpv in English, so they can't be translated into Italian. Of course, if no one reminds them, they won't know or understand them at all.
Please help to confirm whether there is a grammar problem, looking forward to your reply again 


-----------------------------------------------------------------------------

percorso di archiviazione del file di dati: data\mpv-easy-data\menu.conf     =======<<<===========

per inviare una serie di scorciatoie a mpv  usa una voce di menu invece della tastiera.

ogni tasto di scelta rapida in una serie di tasti di scelta rapida viene inviato separatamente a un breve intervallo.

Viene usato uno spazio per separare ogni tasto di scelta rapida in una serie di tasti di scelta rapida.

Avviso:

non attivare mouse e tastiera durante l'esecuzione.

usa la rappresentazione del tasto di scelta rapida in input.conf, ad esempio:

invio=enter   ==========<<<<============

spazio=space   ==========<<<<============

si applica a:

1. non voglio memorizzare i tasti di scelta rapida.

2. cose che possono essere completate premendo a turno più tasti di scelta rapida.

3. eseguire automaticamente determinati comandi nella finestra della riga di comando di mpv.

esempio:

nome voce menu:

questo è il nome di una voce del menu

tasto scelta rapida:

ctrl+a alt+b shift+c ctrl+shift+d

invia dopo aver premuto la voce del menu [questo è il nome di una voce di menu]:

ctrl+a

aspetta qualche centinaio di millisecondi

alt+b

aspetta qualche centinaio di millisecondi

shift+c   ==========<<<<============

aspetta qualche centinaio di millisecondi

ctrl+shift+d   ==========<<<<============

esempio:

tasto di scelta rapida:

` s e t space v o l u m e space 8 8 enter esc   ==========<<<<============

apre una finestra della riga di comando

entrare ed eseguire: set volume 88   ==========<<<<============

esci dalla finestra della riga di comando

Avviso:

in modalità GUI nativa mpv, se sono abilitate più istanze

1. non cambiare finestra durante l'esecuzione

2. ti consigliamo di disattivare la funzione superiore adesiva.

-------------------------------------------------------------------------

**Comment by bovirus** [comment]
@422658476 

percorso archiviazione file dati: data\mpv-easy-data\menu.conf

the string is ok now?

**Comment by 422658476** [comment]
@bovirus

There is one item left unconfirmed: 

--------------------------------------------

enter and execute set volume 88

--------------------------------------------

This sentence means to open the command line window, enter the English text "set volume 88" in the command line window, and finally press the Enter key to execute it 

If translated into Italian, whether the following translation is correct, this is the result of my wild guess. 

=============================

entrare ed eseguire: set volume 88

=============================

**Comment by 422658476** [comment]
@bovirus

bovirus, don't forget that the last translation has not been confirmed, looking forward to your reply: 

enter and execute set volume 88   ==>>  entrare ed eseguire: set volume 88 ？？？？

**Comment by bovirus** [comment]
@422658476 

enter and execute set volume 88 ==>> accedi  ed esegui set volume 88

**Comment by 422658476** [comment]
ok,I will upload the latest language files and screenshots later, thank you very much

**Comment by 422658476** [comment]
@bovirus

This is the screenshot after the language update, thank you very much, I will close this issue 

![1](https://user-images.githubusercontent.com/37802190/155884739-3a5920e8-aaa1-4900-b402-5de8c3f163eb.png)


![2](https://user-images.githubusercontent.com/37802190/155884888-48f2ae3c-dc64-4c3d-8f65-fecf3e5e6fc6.png)

![3](https://user-images.githubusercontent.com/37802190/155884895-43c4aa67-958c-4633-b21d-3ad1d72cc773.png)

![4](https://user-images.githubusercontent.com/37802190/155884903-51512efd-2bc9-42e1-a774-e886b6c55eaa.png)

**Comment by bovirus** [comment]
@422658476 

"Avanzamento aggiornamento in tempo reale quando barra di avanzamento viene..". (too long and truuncated) replaced by
Aggiornamento in tempo reale quando la barra avanzamento viene trascinata"

In the last table after "Avviso" seems that there is a new line not necessary

**Comment by 422658476** [comment]
The second problem has been fixed, the blank line has been removed from the uploaded language file, the first problem will be fixed tomorrow, thank you very much

**Comment by 422658476** [comment]
@bovirus

I have updated the Italian file and uploaded it, here is the updated screenshot, I will close this issue, thanks a lot. 

![1111](https://user-images.githubusercontent.com/37802190/155939136-d7278d4b-fbb5-4ecc-ab0d-651794feb372.png)

![222](https://user-images.githubusercontent.com/37802190/155939163-f587ce5b-4687-4cab-a92d-8e577c8e08a8.png)

**Comment by bovirus** [comment]
@422658476 

Adjustment range: 0%-100%
Calculated based on available desktop area, initial window size, and settings interface size.
Notice:
Pixels are not supported as units of measurement.

Intervallo regolazione: 0%-100%
Calcolato in base ad area desktop disponibile, alle dimensioni iniziali finestra e interfaccia impostazioni.
Avviso:
I pixel non sono supportati come unità di misura.

Thanks.

**Comment by 422658476** [comment]
@bovirus
you missed this sentence ：

初始窗口位置(XY轴)*
initial window position (XY axis)*

**Comment by bovirus** [comment]
@banana

initial window position (XY axis)*

posizione iniziale finestra (assi XY)*

**Comment by 422658476** [comment]
@bovirus

I have uploaded the latest language files,
 here are the screenshots,
 I will close this issue, thanks a lot. 

![111](https://user-images.githubusercontent.com/37802190/156409615-e5986234-015c-42c3-8155-1c658e691fc3.png)
