### ISSUE TITLE
這些主題在哪裡可以下載？

### ISSUE THREAD

**Issue by lyturn** [422658476/MPV-EASY-Player#41]
![mpv-easy-player-6](https://user-images.githubusercontent.com/91406367/163114193-42c2ed55-be4b-484b-bc43-49e4d9d014cb.jpg)

**Comment by 422658476** [comment]
设置界面-左侧栏【osc】- osc样式

**Comment by lyturn** [comment]
我是說在mpv-easy-data/osc-style文件夾下怎麼找不到這些主題。

**Comment by 422658476** [comment]
图中用于无边框gui，无边框gui不是mpv自带的osc.lua渲染的，它是qt界面。
mpv原生gui 由它支持的osc.lua渲染osc，额外的osc只有文件夹下设计的那三种。
2者是完全不通用的
