### ISSUE TITLE
mpv在没有独显直连的笔记本上播放视频时，优先调用核显，独显摸鱼，软件设置里无法识别多个显卡

### ISSUE THREAD

**Issue by 0391** [422658476/MPV-EASY-Player#42]

**Comment by 422658476** [comment]
你这个要向mpv官方提交issue，因为这个是mpv自己判断的。要么这是一个issue，要么可以通过设置修正，但这个都要以mpv官方给与的issue回复为准
没有问题请关闭这个issue。

**Comment by 0391** [comment]
> _No description provided._
