### ISSUE TITLE
考虑登陆微软商店吗？微软商店已经开放Win32应用。

### ISSUE THREAD

**Issue by EcoRII** [422658476/MPV-EASY-Player#44]
微软商店可以自动更新，比较方便。

**Comment by 422658476** [comment]
暂时不会考虑登陆，这个播放器也不会添加更新检测和自动更新，是否想要升级全由用户自己决定。
mpv-easy player是个绿色软件，它没有真正意义上的安装过程和卸载，登录商店肯定必须添加额外无用的安装代码，这会让打包复杂化，甚至可能必须要变成当前版本+商店版2个版本，用户也会因此造成困扰。
mpv-easy player因为绝大部分代码必须闭源(因为一开始就使用了和其他闭源软件相同的代码)的关系，所以可能存在违反各种开源协议的问题，登录商店可能影响更加不好。

**Comment by 422658476** [comment]
@EcoRII 没有问题请关闭这个issue
