### ISSUE TITLE
请教，IPTV列表如何显示？

### ISSUE THREAD

**Issue by 3538532** [422658476/MPV-EASY-Player#45]
导入的IPTV列表能自动播放，但是没法选台，如何调出列表呢？

比如这个IPTV：
https://raw.githubusercontent.com/iptv-org/iptv/master/streams/cn.m3u

**Comment by 422658476** [comment]
如果你已经把这个m3u文件保存到本地，并且使用MPV-EASY Player双击播放了。
那么请使用菜单中的【显示高级播放列表】显示列表，因为这个文件实际上就是一个播放列表文件。
在无边框gui模式下，点击osc中的当前正在播放的视频文件名（这个的文件名应该是index.m3u8），那么也会触发高级播放列表的显示。
如果想要【换台】，请使用osc中的[<][>]按钮切换到上一个或者下一个。
如果想要直接跳转到某个台，那么显示高级播放列表后，按下键盘上的【上】【下】键，就可以选择条目，之后按下回车播放选择的台。如果不清楚请看设置界面-快捷键:播放列表.
没有问题请关闭这个issue

**Comment by 422658476** [comment]
如果你觉得这样操作繁琐，那么请变换一下使用的思路:
把每个需要播放的台都保存成一个单独的m3u文件，那么每次要打开这个台就像播放一个本地视频一样在文件管理器中双击这个m3u文件就行。
创建m3u文件也很简单，新建一个txt文件，用记事本打开含几千个台的m3u文件，复制其中一行，一行网址就是一个台，把复制的文本粘贴到txt中，最后把txt改成m3u后缀即可。
这样也方便今后每个台网址的替换，因为几千个台太多重复的，每次都用播放列表选台太浪费时间

**Comment by 3538532** [comment]
> 如果你已经把这个m3u文件保存到本地，并且使用MPV-EASY Player双击播放了。 那么请使用菜单中的【显示高级播放列表】显示列表，因为这个文件实际上就是一个播放列表文件。 在无边框gui模式下，点击osc中的当前正在播放的视频文件名（这个的文件名应该是index.m3u8），那么也会触发高级播放列表的显示。 如果想要【换台】，请使用osc中的[<][>]按钮切换到上一个或者下一个。 如果想要直接跳转到某个台，那么显示高级播放列表后，按下键盘上的【上】【下】键，就可以选择条目，之后按下回车播放选择的台。如果不清楚请看设置界面-快捷键:播放列表. 没有问题请关闭这个issue

谢谢回复，你说的这个播放列表我也看到了，因为有视频背景，所以有些不太方便看，操作上说实话也不太便捷。
能不能提个小建议：把这个播放列表放到外面去？需要时调用出来。
再次谢谢！

**Comment by 422658476** [comment]
播放列表需要兼容2种不同的gui和多实例等其他东西，如果放到外部，在另一种gui下很难正常工作。
你要的那种播放列表界面实际就是存放一堆m3u文件的文件管理器界面。
高级播放列表的背景透明度你可以在rjno1.conf中手动调整，调整也会影响osd。
osd-back-color=1.0/1.0/1.0/0.22
osd-border-size=1
其中的0.22是透明度，你可以改成0.5等。
1可以改成2，让文字边框更粗。
如果想要让调整只影响高级播放列表，请调整高级播放列表脚本文件或者它的设置文件:

  --playlist ass style overrides inside curly brackets, \keyvalue is one field, extra \ for escape in lua
  --example {\\fnUbuntu\\fs10\\b0\\bord1} equals: font=Ubuntu, size=10, bold=no, border=1
  --read http://docs.aegisub.org/3.2/ASS_Tags/ for reference of tags
  --undeclared tags will use default osd settings
  --these styles will be used for the whole playlist
  style_ass_tags = "{}",

这个设置可以更改显示样式，使用方式参考上方以--开头的注释。

 --osd timeout on inactivity, with high value on this open_toggles is good to be true
  playlist_display_timeout = 5,
调整高级播放列表多少秒后自动隐藏

**Comment by 3538532** [comment]
> 播放列表需要兼容2种不同的gui和多实例等其他东西，如果放到外部，在另一种gui下很难正常工作。 你要的那种播放列表界面实际就是存放一堆m3u文件的文件管理器界面。 高级播放列表的背景透明度你可以在rjno1.conf中手动调整，调整也会影响osd。 osd-back-color=1.0/1.0/1.0/0.22 osd-border-size=1 其中的0.22是透明度，你可以改成0.5等。 1可以改成2，让文字边框更粗。 如果想要让调整只影响高级播放列表，请调整高级播放列表脚本文件或者它的设置文件:
> 
> --playlist ass style overrides inside curly brackets, \keyvalue is one field, extra \ for escape in lua --example {\fnUbuntu\fs10\b0\bord1} equals: font=Ubuntu, size=10, bold=no, border=1 --read http://docs.aegisub.org/3.2/ASS_Tags/ for reference of tags --undeclared tags will use default osd settings --these styles will be used for the whole playlist style_ass_tags = "{}",
> 
> 这个设置可以更改显示样式，使用方式参考上方以--开头的注释。
> 
> --osd timeout on inactivity, with high value on this open_toggles is good to be true playlist_display_timeout = 5, 调整高级播放列表多少秒后自动隐藏

谢谢回复，我来试试。
