### ISSUE TITLE
Streamlink

### ISSUE THREAD

**Issue by trimechee** [422658476/MPV-EASY-Player#47]
Hello, it will be great to add support of streamlink just like yt-dlp so our beloved MPV-EASY-Player plays even more videos from streaming sites !

https://github.com/streamlink/streamlink

Thank you very much !

**Comment by 422658476** [comment]
This does not require any support, just add the path of mpv-easy player in its settings file, or use the --player parameter to specify the path of the player when using it on the command line, and then you can call the specified player to play

**Comment by trimechee** [comment]
Wouah ! great ! thank you very much :)

I specify that I would like to use streamlink without command line which I find difficult and complicated and uncomfortable, i.e. I would like to copy paste the streaming link in MPV-EASY-Player which offers me options to choose the video reslution quality SD or HD or 4K and an option to choose and increase the network cache or timeshift if my internet connection is weak, or add this very important option: " Download media data independently from playback
If this option is checked, filter performs media file download independently of playback. Let it continue downloading even when playback is paused.

This approach is useful when you have slow or unstable Internet connection (so playback is stuttering), or when you need to seek a lot within a file. "

many people  don't know or don't like to use CLI command line softwares that's why i asked for streamlink support by our beloved MPV-EASY-Player , i was inspired by "Gridplayer" which has recently add native support of streaming sites and adding streamlink support without the need to use the command line

**Comment by 422658476** [comment]
One of the reasons the player does not provide a menu item to open video links is that online video links need to be extracted, which is difficult to obtain. This function is usually meaningless.
But mpv itself provides the function of opening online videos, so this player actually works. You can refer to the last closed issue No. 45, which is also discussed.
If you want to open the online video link in an easy way, you only need to save the video link to a txt text, and then rename the file to a playlist file with the suffix m3u8, double-click to play, Multiple video links can be added to this file.
If you don't want to use the command line to open the link, but at least you need to use streamlink's command line to let it return all the video link addresses, so you can paste it into the playlist file. I don't know if it has this feature, and the video address is likely to change frequently, which requires you to read its documentation.

**Comment by trimechee** [comment]
Very interesting and useful !! Thank you very much for these important explanations and your help :)
