### ISSUE TITLE
gpu-hq profile option? (gpu-hq配置文件选项?)

### ISSUE THREAD

**Issue by ccrowles** [422658476/MPV-EASY-Player#49]
Does MPV Easy player have [gpu-hq profile option](https://github.com/mpv-player/mpv/blob/master/etc/builtin.conf#L43)? Because a group who does fanmade subtitles for anime [recommends to turn on gpu-hq profile](https://gist.githubusercontent.com/motbob/754c24d5cd381334bb64b93581781a81/raw/49328c7b6f905deadca7f9b63258b2dbf7915c08/playback_guide) for optimal video quality of their work.

MPV Easy播放器是否有[gpu-hq配置文件选项](https://github.com/mpv-player/mpv/blob/master/etc/builtin.conf#L43)？因为一个为动漫制作粉丝字幕的团体[建议打开gpu-hq配置文件](https://gist.githubusercontent.com/motbob/754c24d5cd381334bb64b93581781a81/raw/49328c7b6f905deadca7f9b63258b2dbf7915c08/playback_guide)，以获得他们发布的最佳视频质量。
(使用Deepl机器翻译进行翻译)

**Comment by 422658476** [comment]
你可以查看data/protable-data/rjno1.conf
其中默认就包含了profile=gpu-hq
mpv会按照这个设置自动使用gpu-hq

**Comment by ccrowles** [comment]
> 你可以查看data\mpv-easy-data\rjno1.conf
> 
> mpv.conf中的所有设置都被转移到了rjno1.conf中， 其中默认就包含了profile=gpu-hq mpv会按照这个设置自动使用gpu-hq

Thanks!

谢谢!
