### ISSUE TITLE
优化默认配置

### ISSUE THREAD

**Issue by Frozen1084** [422658476/MPV-EASY-Player#50]
中低配置的电脑，播放一个30GB的4K视频，都用默认配置，官方MPV，会占用60%的GPU，而 MPV-EASY占用几乎100%。
测试PotPlayer，也只使用70%左右。

**Comment by 422658476** [comment]
这个和MPV-EASY无关，和你电脑显卡的性能有关。
mpv、MPV-EASY默认都是使用mpv处理画面，2者没有任何差异
如果默认使用cpu解码，那么cpu占用高，gpu占用低。
如果使用gpu解码，那么cpu占用低，gpu占用高。
你需要观察2个播放器在播放4k时的cpu和gpu的表现，2者的差异可能只是一个使用cpu解码和一个使用gpu解码。
MPV-EASY默认使用gpu解码，而mpv默认可能是cpu解码。
如果显卡性能不足以支撑4k的播放，那么就会出现显卡100%的情况，因为显卡资源已经耗尽。
如果想要在不升级硬件的情况下解决这个问题，2个方法：
1、设置中切换到软解

2、请使用这个脚本

https://github.com/422658476/MPV-EASY-Player/blob/master/portable-data/scripts/use-cpu.lua

请参考代码中的注释和代码本身。

默认代码的意思是当检测到播放的视频宽度大于3000（注释部分也支持检测高度大于2000），并且检测视频是h264还是h265格式，让mpv核心自动切换到cpu解码或者gpu解码。

**Comment by Frozen1084** [comment]
你前面还说二者的默认配置是一样的，后面就又说"MPV-EASY默认使用gpu解码，而mpv默认可能是cpu解码。"，前后矛盾。

**Comment by Frozen1084** [comment]
啊抱歉，我是PotPlayer用户，尝试MPV遇到问题就顺便报了下。
删除"gpu-hq"后与官方表现保持一致了。
