### ISSUE TITLE
添加vo=gpu-next设置选项

### ISSUE THREAD

**Issue by gbaoye** [422658476/MPV-EASY-Player#51]
真的很需要

**Comment by 422658476** [comment]
这个不稳定的选项不会被添加到设置中，就像hwdec=xxx中有些不稳定的选项也不会被添加到选项中一样。

**Comment by 422658476** [comment]
@gbaoye 没有问题请关闭这个issue

**Comment by gbaoye** [comment]
@422658476 这个是支持杜比视界唯一的选项，我觉得选择权应该交给用户，默认设置就是稳定的

还有那个添加代码，每次保持设置，我都要重新添加

还有一个中和的解决方法，就是在设置文件里添加这个代码后，能不能在你的设置里显示这个额外的选择

**Comment by gbaoye** [comment]
https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU

**Comment by 422658476** [comment]
请把profile=gpu-hq,ini-custom这行改成这个格式即可正常读取：
profile=“gpu-hq,ini-custom”
由于qt读取这个文件并保存后，格式自动会有变化：
profile=gpu-hq,ini-custom【qt改写前】
profile=gpu-hq, ini-custom【qt改写后，逗号后面多了个空格】
由于多出了一个空格，所以mpv就不认[ini-custom]，实际上mpv此时在读取[ ini-custom]。
如果不想使用：
profile=“gpu-hq,ini-custom”
那么请写成：
profile=gpu-hq, ini-custom
以及
[ ini-custom]
（也就是2个ini-custom之前都添加个空格）
--------------------------------------------------
这种方式是添加额外设置最好的方式，这些用户自定义添加的设置不能被放在设置界面，因为用户自定义的设置极有可能会覆盖设置界面已有的设置，这会导致，比如
设置界面音量为50，用户自定义音量为70
这会让用户觉得设置界面上的音量选项有bug，调整后无效，因为此时音量永远为70。
--------------------------------------------------
gpu-next说明文档中已经写明是个【Experimental video renderer based on libplacebo.|基于 libplacebo 的实验性视频渲染器】，所以它不会被放在设置选项中，因为稳定性是第一位的。如果gpu-next中已经改写的代码mpv官方觉得已经稳定和成熟，自然会把这些代码迁移到gpu设置中，这只是时间问题。
gpu-next目前远远没有达到稳定可用的状态，它在windows下可能表现出比较良好的一面，不过至少在linux下无法打开视频、导致mpv进程残留在内存中的概率几乎有100%，这个选项是非常不完善的。
--------------------------------------------------
如果你想使用gui临时激活这个选项，那么使用设置-菜单-自定义菜单是最好的方式。
比如菜单项名称：
切换到vo=gpu-next
快捷键：
` s e t space v o space g p u - n e x t enter
当点击菜单项，等待其自动输入完毕，就会在mpv的命令控制台看到vo被切换到了gpu-next
如果想要切换后自动关闭控制台，请把快捷键改为：
` s e t space v o space g p u - n e x t enter esc
之后可以手动按下【`】，也会看到vo被切换到了gpu-next

**Comment by gbaoye** [comment]
@422658476 好的，解决了

**Comment by 422658476** [comment]
@gbaoye  没有问题请关闭这个issue

**Comment by gbaoye** [comment]
@422658476 还有窗口化播放的大小调节好像失效了，我调屏幕70%的大小，结果什么分辨率的电影都是满屏，是是把电影拖动到播放器的

**Comment by 422658476** [comment]
因为这个设置叫做【开启时】窗口的大小还有位置，如果你是打开播放器后使用拖放在打开电影，那么打开播放器算作开启时，而拖放打开则不是

**Comment by 422658476** [comment]
@gbaoye 没有问题请关闭这个issue

**Comment by 422658476** [comment]
@gbaoye 没有问题请关闭这个issue
