### ISSUE TITLE
新用户的几个问题

### ISSUE THREAD

**Issue by Frozen1084** [422658476/MPV-EASY-Player#52]
1，播放这个视频，快进几秒后会幻灯片几秒才正常播放。
把 "hwdec=auto-safe" 删除后就正常了，我不确定这是不是BUG。

magnet:?xt=urn:btih:13bfd93626bb9d9f2aba795e0590f69baa6b889c

2，能把两个主要的工具条设置为，鼠标移动它们上方时才显示吗？
现在只要在窗口移动鼠标它就会显示，很没必要。

3，我把所有选项都找了，也没有发现隐藏最下方那个进度条的方法。请问如何隐藏它？

**Comment by 422658476** [comment]
1、请勿删除设置，而是通过在设置界面更换成其他选项进行比较。如果你删除hwdec=auto-safe，那么mpv会切换会默认设置，也就是hwdec=no，也就是变回软解，而不是硬解。
2、是否是视频问题请自己做横向比较，如果其他视频在相同操作下正常，只有这个视频有问题，那么就是视频问题，这个是非常好排除的。
3、按照你的操作方式，幻灯片问题有可能是显卡性能太低导致的，在测试时请打开任务管理器监控gpu使用率
4、快进后幻灯片还有一种已知可能。设置中启用了【进度条拖动时实时更新进度】，那么释放鼠标时会对视频产生2次定位，一次大概定位，一次精确定位，使用时有可能会卡一下，但是不会卡几秒。如果你使用的时快捷键快进，那么通常不会有卡顿问题。

-------------------------------------------------------------------------

2个控件本身就是移动到它们上方才显示。2种不同gui虽然有些差异但都是使用类似的逻辑：

在y轴上把视频窗口区域分成三份，上方小块区域、中间大块区域、下方小块区域，鼠标只有移动到上方和下方小块区域才会显示，在中间大块区域移动鼠标是不会触发显示的。如果你不想要移动鼠标就显示，只需要把鼠标放在中间即可。

需要注意的是：上方工具条向下几十个像素和下方工具条向上几十个像素也算在上方小块区域和下方小块区域，也就是鼠标在y轴要远离工具条几十个像素才算进入中间区域。这种灵活的逻辑能够适合大部分人的不同喜好，有人想要移动立刻显示只需要把鼠标放在上方小块区域和下方小块区域，临时想要在这2种方式间切换也只需要改变鼠标停留位置即可。

还有一种：【多少毫秒后自动隐藏osc界面】如果设置从3000ms改成比如99999999ms，那么才会变成鼠标移动到窗口中，2个工具条不会自动隐藏。

----------------------------------------------------------------------------

下方一条线的迷你进度条是必须要有的，因为它还要用来检测哪个窗口处于焦点状态，如果你不想要看到这个迷你进度条，请点击上方工具条最左侧的锁定图标进入锁定模式，或者点击鼠标右键也会进入锁定模式，锁定模式不显示任何工具条。

如果你说的是【mpv原生gui】底部的迷你进度条，不要勾选【总是显示osd进度条。。。。】就能不显示。

----------------------------------------------------------------------------

**Comment by Frozen1084** [comment]
谢谢。
1，似乎在ffmpeg系播放器都不正常。mpc_be正常。
2，"只需要把鼠标放在中间即可"，这个有点强人所难。所以这个上中下三个区域的划分是可以定义的吗？还是说强制三均分。可以定义的话就解决问题了，把上下设置为30，其他为中，就OK了。
3，我不想每个视频都要手动隐藏它一次。能不能想个办法默认隐藏呢？

**Comment by Frozen1084** [comment]
第4个问题。
我下载的这个地址的4K webm 文件
https://www.youtube.com/watch?v=6Gw8xStM-TQ

这个视频很奇怪，通过左键在进度条调整进度时，有很大的延迟，经常出现~1秒的延迟才会继续播放。
而PotPlayer几乎没有延迟

**Comment by 422658476** [comment]
不是鼠标一定要放到你认为的中间，你只要把鼠标远离上下工具条10-30个像素就到所谓的中间区域了，窗口估计70%的区域都算中间。这个不需要调整，上下区域究竟有多大是根据工具条的高度加几十像素，这个十分合理的，就像windows的任务栏一样。想要中间区域大你就用一行的工具条，想要稍微窄点就用2-3行的工具条。

迷你进度条是必须的，因为窗口是否处于焦点是每个窗口必须要有的基本功能，一厢情愿的要取消，请你想想取消后的ui交互问题，就像每个操作系统为了解决交互问题为什么都要引入焦点功能一样。

**Comment by 422658476** [comment]
1.进度条调整有延迟这个和你电脑的性能有关。

2.为什么PotPlayer几乎没有延迟而mpv会有延迟：
因为potplayer可能使用的是非精确的定位，也就是使用百分比定位，这种定位是不精确，有一定偏差，但是这种定位方式性能很好，而mpv-easy player 默认使用的是精确定位，你点击到多少秒，他就定位到多少秒，1秒都不会差（所有和时间有关的代码为了这种完全的精准进行了非常多的调试，也重写过很多次），这种定位方式性能会差一些，电脑性能如果较差就会遇到延迟。所以建议比较这个差异的时候也请打开任务管理器查看资源消耗的差异。

如果想要更快的定位，请启用【进度条拖动时实时更新进度】。启用后，当鼠标按住后在进度条上拖动，那么每次都是百分比定位，性能会高很多，此时你可以比较是否延迟缓解很多，当你定位到需要观看的时间点周围在释放鼠标，释放鼠标行为会触发一次百分比定位后在触发一次精确定位，从而做到百分比定位时精度依然没有偏差，所以鼠标释放这个行为时应该还会出现1秒延迟和画面有卡顿一下。

最后你可以在设置中改为软解，来测试精确定位是否会快一点。反过来也是一样。

**Comment by Frozen1084** [comment]
你这么强烈的主观，好太多、人性化的，真没必要说下去了。
"想要看界面，必须要鼠标移动到界面上才显示"，和"小心翼翼移动鼠标以避免工具栏遮挡视频"，这两个哪个更适于看视频，咱们各有判断吧。


你那些交互的问题，好像没有一个是问题。

在一个失去焦点的窗口上点击左键和一个正在使用的窗口上点击左键，请问会有什么不同？ ->没有不同。
一个应该只会触发获取焦点行为而不应该触发暂停， 另一个只出发暂停，点击后每次还要想想这次怎么没暂停？-> 一个暂停，一个激活并暂停。你要觉得这会混淆激活这个操作，就把暂停换成双击或者右键呗
如果在一个失去焦点的窗口上直接点击进度条，是直接响应这种定位需求，还是只是获取焦点？->激活并定位
甚至失去焦点的时候要不要鼠标移动触发界面显示？ ->显示
失去焦点的时候使用滚轮是否要触发音量调节？->调节，WIN10 就有滚轮穿透了
失去焦点是要不要鼠标在音量图标上时展开音量条。->这些问题根本没毛意义，不激活也是可以接收鼠标事件的，常规响应就行

**Comment by 422658476** [comment]
你先搞清楚谁的工具栏在遮挡视频，potplayer工具条是占据底部一整条的，mpv则是为了减少遮挡只有1000左右的宽度，这种短的工具条还有一个人性化的特点就是控制时鼠标只需要左右移动短距离，不需要从显示器最左侧和最右侧来回大幅移动。如果开启工具条半透明，potplayer背景加文字都是半透明，mpv文字不透明只背景半透明，谁更加遮挡视频谁更加看不清。
mpv这种工具条就像是一个只有中间部分，2边都透明的potplayer工具条，它的显示和隐藏逻辑都类似，为什么2边透明后相同的交互反而不习惯了。potplayer这种鼠标移动到工具条上才显示还存在工具条显示会有一定延迟的问题，mpv为什么在距离工具条20 -30像素就开始显示，就是为了在鼠标快要进入工具条区域时显示就准备完毕，避免视觉操作上的停顿。
喜欢每次都要把鼠标非要移动到工具栏区域才显示，如果真的像你那么设计，用户每次显示界面非要把鼠标移动到显示器中间底部那一小条的位置，需要移动鼠标的距离比当前这种不知道要多多少。
还有当前ui交互不需要你小心翼翼，只要你稍微改下鼠标停放的位置，mpv这么简单的ui交互都理解不了，你还是自己想想吧。

简而言之，如果potplayer这种什么都没有做优化的最简单的逻辑最优，那mpv设计这种交互的人是真的吃饱了撑的，mpv easy还学这种交互那更是吃饱了撑的。

你看看你自己对于逻辑交互的回答，要么跳过不答，要么这种答案，这么优秀的逻辑交互还是你自己一个人留着用吧，这个就不要在讨论了，这种ui交互不会被接受。

**Comment by Frozen1084** [comment]
你连与potplayer比较的重点都抓不住，两大段文字简直在自我陶醉。
potplayer的工具栏再大再难看，但它至少可以按需出现，不会在你不需要它显示的时候显示，不会骚扰用户。
至于无需小心，只要控制好鼠标就行。拨鼠标线岂不是更秀。
我找了一遍也没找出哪个回答是跳过的，算了，那些问题本来就透着蠢，确实没必要再说。

**Comment by 422658476** [comment]
真是神仙难救，说白了就是为了自己的喜好其他什么功能都能舍弃，你那鼠标就一定要放在底部工具条周围。你只要像pot一样把鼠标放在工具条上面一点左右移就不会出现了，这个和pot有什么区别，所有操作都一样会一个按需显示另一个不安需显示？

我问你，第一条问题:多个只有边框的窗口怎么判断哪个在焦点上？你连这个都看不见？我来告诉你，每个窗口都一样你自己靠猜吧。
为了去掉迷你进度条，还出暂停还双击，那全屏改三击？点一下窗口就暂停一次你都能接受，双击暂停都能接受，底部占用那点地方眼中钉接受不了？
为了自己幻想的功能，什么都能不顾及，你自己回答说出来给人家听不脸红吗？这种东西你自己用。

**Comment by 422658476** [comment]
我还可以给你在出个馊主意，就是改变1px像素的边框的颜色来解决焦点问题，这样就完美解决了
