### ISSUE TITLE
Change max History Items

### ISSUE THREAD

**Issue by Milor123** [422658476/MPV-EASY-Player#54]
Helloooo guys !!. I would like change the number of items MAX saved in the history. I want that more items will be shown !

![image](https://user-images.githubusercontent.com/14153649/199124695-db82426a-8f65-48f5-a19e-aae480eb763e.png)

How can change it? I'm in windows 10
Thank you very much. I love this player !!!

**Comment by 422658476** [comment]
This feature will be added in the next version, thank you very much。

**Comment by 422658476** [comment]
@bovirus

hello bovirus:

I'm going to trouble you again.

The code for this new function is complete, but for this a new option needs to be added, which requires you to translate into Italian:

---

chinese：

【打开最近播放的文件】菜单项能显示的播放历史的最大数量

english：

[Open recently played file] menu item can display the maximum number of play history

Italian:

——————————————————————————————————

**Comment by bovirus** [comment]
@422658476 

Thanks.

iitaliano:

La voce di menu [Apri file riprodotto di recente] può visualizzare un numero max di file riprodotti da crionologia

**Comment by 422658476** [comment]
@bovirus

hello bovirus:

thank you very much for your quick reply. According to this, I have uploaded the latest translation file. Below is the screenshot of the translation, please refer to it.

![history-max-item](https://user-images.githubusercontent.com/37802190/199413150-ac276ab9-a52e-471d-9bb6-c79a364a3c9e.png)

@Milor123 

If there is no problem please close this issue, a new version will be released in the next few weeks, thank you very much.

**Comment by Milor123** [comment]
Thank you very muchhh guys :D
