### ISSUE TITLE
怎么启用缩略图呢?

### ISSUE THREAD

**Issue by Xandaboss** [422658476/MPV-EASY-Player#57]
我想要像https://github.com/hooke007/MPV_lazy 里一样的缩略图功能，MPV-EASY-Player里能否启用这样缩略图？

**Comment by 422658476** [comment]
mpv原生gui模式下，你可以使用github 上其他人写的mpv的脚本来实现鼠标在进度条上有缩略图，脚本中的这类功能只能在mpv官方osc.lua中生效。
mpv easy gui下，没有这种功能，也不会实现这个功能，因为从mpv关键帧中提取很多图片会影响性能，如果想要类似功能，请开启设置：进度条拖动时实时更新进度。

如果是截图功能，请使用github上其他人提供的mpv截图脚本

**Comment by Xandaboss** [comment]
@hooke007

**Comment by 422658476** [comment]
缩略图如果你使用mpv原生gui，并且使用mpv脚本实现，那么脚本提取图片显示图片可能能够直接在内存中进行。
但很多脚本的缩略图可能还是把它保存到硬盘的配置文件夹的某个缓存文件夹中后在处理。

如果是mpv easy gui下实现，由于不能直接读取mpv的内存，那么只能让mpv截取图片保存到硬盘的某个文件夹，然后才能让mpveasygui.exe读取后在显示在界面中，请你自己想象一下一秒钟要同时保存10张图片并读取10张，并且删除10张图片要消耗多少资源，这种功能在高负载的情况下最容易出现性能瓶颈导致一卡一卡的。

更加不幸的是，如果你在播放4K视频，需要消耗更多资源的时候，mpv截取的图片也是更大的尺寸，也就是4K的图片，这是火上浇油。

实际上这样的功能应该尽可能的避免出现在程序中，而不是去实现它。

**Comment by 422658476** [comment]
@Xandaboss 

mpv中有2个非常有趣的快捷键，对于你来说可能非常有用

标记位置：Shift+BACKSPACE

返回标记位置：Shift+Ctrl+BACKSPACE

你可以先按下【标记位置】快捷键，mpv会记住当前播放的时间点，之后你可以随意拖动、点击进度条，或者快进快退预览视频的任何部分，最后按下【返回标记位置】快捷键就能回到之前记住的时间点继续播放。

这可以在完全不影响性能的情况下更好的满足预览的愿望。

如果你不想要记住这2个快捷键，可以把它们添加到自定义菜单中，使用菜单进行操作。

菜单项名字：     快捷键：
标记位置            ctrl+shift+bs
返回标记位置     shift+bs
