### ISSUE TITLE
建议增加兼容 杜比视界

### ISSUE THREAD

**Issue by hhun** [422658476/MPV-EASY-Player#59]
建议 `MPV-EASY Player/data/mpv-easy-data/rjno1.conf` 文件在 `[ini-rjno1]` 后面增加以下配置
```
######## 兼容杜比视界 Start ########
vo=gpu-next			#调用最新渲染器libplacebo
gpu-context=d3d11		#实时渲染引擎
d3d11-output-csp=pq		#老版本 HDR播放必备，仅Win10提供的 API 可激活
vf="format:dolbyvision=yes"	#杜比视界滤镜
d3d11-output-format=rgb10_a2	#rgb10_a2 rgba16f rgba32f
blend-subtitles=no		#HDR视频外挂字幕必备
######## 兼容杜比视界 End ########
```
这样播放杜比视界的视频就不会偏色。
好像还需要在Gui设置程序里面兼容，不然保存下又没有上面的这些配置了。

**Comment by 422658476** [comment]
请使用这种方式激活你写的那些配置 ：

https://github.com/422658476/MPV-EASY-Player#%E7%BB%99%E8%AE%BE%E7%BD%AE%E7%95%8C%E9%9D%A2%E7%9A%84%E8%AE%BE%E7%BD%AE%E7%BB%99%E4%B8%8E%E9%80%89%E9%A1%B9%E4%B8%AD%E4%B8%8D%E5%8C%85%E5%90%AB%E7%9A%84%E5%80%BC
