### ISSUE TITLE
关于播放m3u的问题

### ISSUE THREAD

**Issue by yushu280** [422658476/MPV-EASY-Player#60]
播放m3u时，能不能增加个播放列表，可以手动选择？目前按F8，只能查看m3u中的少部分的目录，无法选择。使用高级菜单，可以用pgDn、pgUP翻页，但由于m3u通常有几百，甚至几千个链接，不知道怎么快捷选择？希望增加个播放列表，可以利用鼠标快速滑动选取

**Comment by 422658476** [comment]
播放列表必须要使用当前高级列表这样的操作方式和交互方式，这样在2种gui中才能通用，界面也不会产生混乱。

m3u中有几百上千个链接通常就是电视台的播放列表，实际上电视台列表根本没有任何实际价值，因为每个台播放几秒后通常就需要不停的缓冲。

如果要管理这种上百个链接的播放列表，建议使用这种方式管理，从而提高效率和增强体验：

https://github.com/422658476/MPV-EASY-Player/issues/45#issuecomment-1174146040

通常当前的高级播放列表已经带有较好的使用体验了，能够胜任正常的几个或者十几个的文件播放。

--------------------------------------------------

如果你需要使用鼠标滑动选取，那么改造当前的高级播放列表是最好的选择，高级播放列表的作者写的代码很好，在这方面改动非常容易。

请打开mpv-easy player\data\portable-data\scripts

把playlistmanager.lua复制一份并重命名成比如playlistmanager-diy.lua，并存放于相同路径，那么就可以获得一个额外的高级播放列表，这个和自带的高级播放列表（playlistmanager.lua）能够同时使用，互相不冲突。

使用文本编辑器打开playlistmanager-diy.lua

在最底部，找到

mp.add_key_binding("ctrl+alt+u", "showplaylist", toggle_playlist)

比如改成：

mp.add_key_binding("F5", "showplaylist", toggle_playlist)

那么就可以使用【f5】显示这个额外的高级播放列表。如果想要使用菜单触发显示这个额外的高级播放列表，请使用自定义菜单

菜单项名字：

我的高级播放列表

快捷键：

f5

使用文本编辑器打开playlistmanager-diy.lua

在最顶部：

  key_moveup = "UP",
  key_movedown = "DOWN",
  key_playfile = "ENTER",

比如改成

  key_moveup = "MOUSE_BTN3",
  key_movedown = "MOUSE_BTN4",
  key_playfile = "MOUSE_BTN1",

f5显示高级播放列表后就可以使用滚轮滚动选取上一个下一个，点击滚轮就播放当前选中的。

你也可以更改高级播放列表的显示时间，这个在超长播放列表下可能有用：

playlist_display_timeout = 5,

比如改成：

  playlist_display_timeout = 999,

那么播放列表在999秒后才会自动隐藏，如果想要手动隐藏，在显示播放列表的情况下再次按下显示高级播放列表的快捷键（例子中为f5），就能隐藏。

快捷键如何书写请参考：

https://github.com/422658476/MPV-EASY-Player#%E5%BF%AB%E6%8D%B7%E9%94%AE

注意不要使用快捷键：
MOUSE_BTN0
MOUSE_BTN2
esc
一个是鼠标左键，一个是鼠标右键，一个是退出键，mpv-easy gui中使用后会同时触发暂停或者进入锁定模式，或者退出全屏，这个是无法避免的。

改造后的lua文件建议备份到其他路径，防止丢失。

**Comment by yushu280** [comment]
谢谢，根据您的建议设置，可以使用了。其实，我更希望有类似于potplayer那种播放表，可以在侧边快速滑动。期待mpv越来越完善易用

**Comment by yushu280** [comment]
mpv-easy挺好用的，就缺一个播放列表。github上有个https://github.com/telppa/mpv-playlist-manager/releases/tag/v1.3，还挺简单好用的，如果mpv-easy能整合一个类似的功能就好啦。谢谢您的mpv-easy，降低了mpv的使用门槛，也挺美观的

**Comment by 422658476** [comment]
这个是无法在mpv-easy player中使用的，它使用了pipe管道和mpv传输数据，mpv-easy也使用这种方式，并且比它先使用，它是不能正常工作的。
这种方式在mpv启用多实例下是根本分不清它们是和哪个mpv窗口一一对应的(看代码，甚至可能不支持多实例)。这也是为什么使用现在这种高级播放列表的一个原因。
