### ISSUE TITLE
添加一个 打开网络串流url的菜单呗

### ISSUE THREAD

**Issue by Yumega** [422658476/MPV-EASY-Player#61]
没有直接播放m3u8链接的菜单入口，测试播放m3u8不方便

**Comment by 422658476** [comment]
请参考:
https://github.com/422658476/MPV-EASY-Player/issues/47#issuecomment-1200457480

**Comment by Yumega** [comment]
> 请参考:
> [#47 (comment)](https://github.com/422658476/MPV-EASY-Player/issues/47#issuecomment-1200457480)

编辑文件不方便，费时，正常播放器都有这个菜单

**Comment by 422658476** [comment]
如果不能接受复制到文件中打开，请尝试其他播放器，这个不常用的功能不会添加到菜单中，原因还是请参考给出的链接
