### ISSUE TITLE
在播放本地视频时，出现帧数不足的问题，60帧仅达到50帧？

### ISSUE THREAD

**Issue by jkqxl** [422658476/MPV-EASY-Player#62]
个人之前一直是在用MPV原版播放器的，今天无疑中发现了这个 MPV-EASY-Player 播放器，尝试了下，有个问题一直无法解决，如标题

在播放本地一个60帧视频时，使用 MPV-EASY-Player 仅能达到50帧左右，最高到51帧，就像是被锁了帧数一样，播放体验不是很流畅，原版则能到达完整的60帧。

测试帧数使用的是 MSI Afterburner 软件

结果显示原版的CPU、GPU占用都不是很高，MPV-EASY-Player的占用接近前面的一倍还多。无边框GUI改用原生GUI也没有任何改善。

没去还不清楚该问题是设置的问题，还是软件本身的问题。

使用系统 win10

**Comment by 422658476** [comment]
请参考:
https://github.com/422658476/MPV-EASY-Player/issues/50#issuecomment-1274819120

通常为gpu-hq这行配置的问题，如果不是请尝试修改链接中提到的其他设置

**Comment by 422658476** [comment]
@jkqxl 没有问题请关闭一个issue

**Comment by jkqxl** [comment]
> @jkqxl 没有问题请关闭一个issue

在删除 profile=gpu-hq 参数后，改用问题已经解决，笔记本的配置还是差了一点

除此之外，近期在尝试中发现了其它的一些问题：
1. 无边框GUI，无法设置 鼠标仅在窗口界面的上下横屏位置显示 OSC，在窗口中间大部分区域不显示，而不是在窗口界面就显示。右键可以取消显示，但毕竟没有自动消失更加舒服、丝滑。已经了解原生GUI可以设置，但对于无边框GUI就是缺陷了。
2. 视频的信息显示不全，很多时候都需要打开信息或文件属性查看，如果没有 OSC 显示也就罢了，但能显示，却仅显示一半，给人的感觉就是，让你吃，但不给吃饱，纠结。其中重要的是关于当前视频流、当前音频流质量的参数，包括视频“数据速率、总比特率，已有帧数、分辨率”、音频“比特率、采样频率，已有声道数”。
3. 音频输出，看信息是默认开启 wasapi，但如果能在设置中显示、修改“是否开启、是否独占”，就更好了。
4. 设置完成后，需要重新打开视频才能生效，这一点有点麻烦，不知能否解决。

嗯，就这些

**Comment by jkqxl** [comment]
突发的一些发散性思维

我想大部分使用 MPV及其衍生软件 的人，都是追求高效，比如快速打开、播放流程、快进不会卡死等。
	既然如此，为什么不在配置上加以区分设置、说明，反而是默认的统一设置
	如果能增加更高性能的画面设置选项，并且给与说明，可以设置启动或关闭，会不会效率更高一点
	一些关键的设置参数
	vo=gpu              #【gpu较费资源，direct3d较省资源，等】
	profile=gpu-hq      #【硬解时让画面更加精细；可能会大大降低笔记本的电池续航时间，在近些年的高分辨率屏幕上（例如“视网膜显示屏”的 MacBook）尤其明显。】
	hwdec=auto-safe     #【硬解允许开启】
	
	icc-profile-auto    #【启用校色，即色彩管理开启】
	blend-subtitles=video    #【将字幕渲染到视频源分辨率并随视频一起缩放并进行色彩管理；保证字幕的分辨率与画面始终一致，避免“画面模糊字幕高清”的情况，保证字幕中“屏幕字”的颜色与画面一致】
	
	scale=ewa_lanczossharp    #【画面拉伸算法 EWA Lanczos ；madVR 中所谓 Jinc，中高端独立显卡推荐】
	
	# 以下是解决“显示器刷新率不是片源帧率的整数倍，造成卡顿；例23.976 fps/显示器刷新率 60 Hz”
	video-sync=display-resample    #【垂直同步？】
	interpolation                  #【启用 interpolation】
	tscale=oversample              #【oversample没有模糊、不平滑/默认mitchell，更平滑、有模糊】
	上面的参数不全，具体可能需要补充测试等
	
	最后，为了完成每个人的最佳配置设置，能否增加 
	1.帧数、CPU/GPU功耗实时显示，不知是否有脚本可以实现该功能，或者类似功能。
	2.设置完成后，应用即可生效，不用确定后关闭设置界面，或者需要重新打开对比
	3.进一步，甚至对应不同的视频设置不同的配置方案，久远年代的视频、动画、4k电影
	
	注：以上都是一些设想，最终能否实现，具体实现难度，本人并不清楚，全看作者自己思量，本着不吐不快的原则，仅此说明。

**Comment by 422658476** [comment]
1.gui这样设计是为了兼容更多人的习惯。鼠标放在不同的位置产生不同的效果，也解决了原生gui鼠标移动时osc会不停出现和消失的问题。只需要让鼠标放在不同位置就能产生不同效果。比如不想要看到osc，鼠标移出界面，或者减少osc显示时间即可。
2.osc本身就是设计为只显示部分信息，因为没有空间容纳更多的。
4.mpv是混合了配置和脚本的，时时生效对脚本来说不现实，重新运行是最好的选择。

其余:设置文件中因为qt的关系，其中所有的注视都会被自动删除，这些是无法保存的。

播放器追求简单易用，只要电脑硬件不是太差当前设置是不会有问题的。

如果你有兴趣，你可以把你了解的这些设置添加到主页中，就像已经添加的那样，因为大部分人是不会去了解这些的，写在网页中更好。这些较为专业的设置本身就是为了让有这些额外需求的人自行添加的，并且随着mpv的改进，有些设置需要改变的，不应该直接写在配置中，这会影响后续版本。mpv-easy本身和mpv一样，只提供较少的东西，其余专业的东西让懂得人自己发挥，这样也能解决众口难调的问题，各自使用自己最喜欢的设置。

**Comment by jkqxl** [comment]
@422658476 

1.对于第一个问题，无边框GUI 在全屏时只能通过鼠标右键取消，一般当视频播放的画面较大时，鼠标要移动到画面外就会出现这样一种情况，那时你需要将注意力从电影画面的关注点转移到鼠标上，找到电脑屏幕上上没有画面的地方去移动，往往需要移动较大的幅度，会造成明显割裂的感觉，降低了视频体验沉浸感。
如果仅仅是设计问题，还是希望增加不同的课修改选项，可以自动影藏，如果由于某些原因无法修正，那唯一的结果就只能是改变习惯，尽管在很多人看来，点击右键的习惯是比较反人类的。

2.只显示部分信息，容纳空间不够，不等于不能优先、或仅显示这些重要的信息。现在的情况是，视频“数据速率、总比特率”、音频“比特率、采样频率等”，并没有添加该选项。越是对于注重高质量视频的媒体工作者、观众，这些信息就越发重要，作者难道不觉得，如果能够增加这些显示信息，会显得软件的规格更高、更专业、更酷吗？

3.后续版本的更新，在不影响功耗的情况下，仅更新特定的文件，几乎是没有影响的吧。把专业的东西变成简单的设置“相比原版MPV需要直接修改代码”，不正是作者一直以来持续做的事情吗，只不过 增加一些高性能的选项，在这方面更加深入。但如果能够做到，我相信 mpv-easy player 会比现在更加受欢迎，也会有更多发烧友前来支持的。

**Comment by jkqxl** [comment]
@422658476
这个世界上感同身受是很困难的事情，如果作者有看到回复，没有其它要讨论的问题的话，本人会关闭这个issue。

**Comment by 422658476** [comment]
1.你说的这个是锁定模式，请不要把它和正常模式混在一起用，正常模式需要使用进度条和它的颜色来提醒你哪个窗口处于焦点，这个是必须的，不能全隐藏。
锁定模式是给用户边看视频边浏览网页使用的，不会因为鼠标偶尔移动到画面区域出现osc。
2.osc叫做播放控制界面，不是给你用来显示你需要的东西的，它的每个按钮都是用来控制画面的。你需要的那些请从[查看视频文件信息]界面查看，并且这些信息本来就应该是从这边查看，osc不是为这些东西服务的。请不要按照设想混用这些不同的东西。
3.mpv和mpv-easy都是一样的，都是在做减法，只保留最少的东西，它们不是为了看起来强大，专业，而是为了更加的简单。而你是要做加法，你想要把你认为需要的所有的东西默认都添加进去。这个理念从开始就是完全不同的，就像是你的这些想法对你来说是必要的，但对mpv-easy来说是完全没必要的，第三个人还有其他想法，请问听谁的。
mpv-easy原创的脚本都只添加了一部分，就是为了尽可能的简单。你想要的这些，也就是你自己需要做的加法，请自己添加，就像mpv默认只带有必要的脚本一样。播放器最后会变为什么样取决于你自己，而你的和其他人的可能是完全不同的。

**Comment by jkqxl** [comment]
好吧，观念不同，相关问题就不再多说了，最后一个问题
![Snipaste_2023-02-11_21-01-31](https://user-images.githubusercontent.com/72729140/218259427-932a32f0-82dd-4ede-b046-31e91fb97898.png)
在运行时，出现一些红字错误，经查看是因为 rjno1.conf 文件中缺失相应参数引起的。

不知能否解决，这些参数能否删除，有什么影响

**Comment by 422658476** [comment]
这些东西必须要报错，因为默认就不需要参数值，它们只需要空着让mpv用默认值即可。当它们需要生效的时候自然会恢复正常。
