### ISSUE TITLE
请求支持 自动旋转

### ISSUE THREAD

**Issue by Masir01** [422658476/MPV-EASY-Player#63]
一些视频 带有rotate标签, potplayer可以支持自动旋转, 但是mpv不行, 大佬可以做一个脚本吗. 可以自动旋转方向的

**Comment by 422658476** [comment]
不清楚不了解这种标签，解决这种问题更好的方式应该是用视频转换器解决旋转问题，一劳永逸。
这种标签的问题也建议直接向mpv官方提交issue，应该会得到更好的答案
