### ISSUE TITLE
[Feature Help] Can make the osc and window controls are displayed separately when hover over the area of each of them?

### ISSUE THREAD

**Issue by BoscoFZ** [422658476/MPV-EASY-Player#64]
I just change a code for add a area show/hide of osc and windowcontrols

```
    -- area for show/hide
    add_area('showhide', 0, osc_param.playresy - 40, osc_param.playresx, osc_param.playresy)
    add_area('showhide_wc', osc_param.playresx*0.009, 0, osc_param.playresx, 30)
```

But both the osc and the window controls still displays simultaneousl when i hover over the area of each of them. It would be great if the osc and window controls are displayed separately like the case in UOSC. For example, when I hover over the bottom part, only the osc part will be displayed, and when I hover over the top part, the windowcontrol will be displayed. Could you please help me solve this problem? Thank you very much.

**Comment by 422658476** [comment]
This function does not need to ask other people for help. If you implement this function, you only need to put the modified code osc.lua in the path of [MPV-EASY-Player/mpv-easy-data/osc-style/], and then You can load this file through the settings interface

**Comment by 422658476** [comment]
I only know a small part of the code in osc.lua. I have not studied this part of the code. If you want to realize this function, you should submit an issue to mpv official. The code contributors of osc.lua should be able to give you the most correct s answer.

**Comment by 422658476** [comment]
@BoscoFZ 
If there is no problem, please close this issue.
 thanks.
