### ISSUE TITLE
windows11下使用mpv-easy-player全屏播放时windows任务栏在最前面

### ISSUE THREAD

**Issue by qq57240** [422658476/MPV-EASY-Player#65]
底下的windows任务栏一直在，无法做到真正的全屏播放

![image](https://user-images.githubusercontent.com/23528139/220624692-b1801a69-37b3-4e90-8028-b5dc64eed516.png)

**Comment by 422658476** [comment]
（1）请问是否在多台windows 11上都是这种情况
（2）请问是否是每次全屏都是这样，还是偶尔某次会出现这种情况

**Comment by qq57240** [comment]
> （1）请问是否在多台windows 11上都是这种情况 （2）请问是否是每次全屏都是这样，还是偶尔某次会出现这种情况

目前只在测试了我自己的这台电脑，系统版本是win11最新的22h2 22621.1265
每次全屏都是如此，设置我改成画面和界面不同时绽放的，因为显示器是23.5:1的，这样设置可以无黑边全屏看电影。

**Comment by 422658476** [comment]
虚拟机中全新安装系统测试后没有发现这个问题，这可能是windows 11某些版本的bug，可能需要更新系统才能解决，没有问题请关闭这个issue。

**Comment by qq57240** [comment]
> 

是我搞错了，全屏按钮是在下面面板上，我以为是右上那个
