### ISSUE TITLE
刚开始用MPV,作者这个界面更美观，但这个怎么启用SVP啊，

### ISSUE THREAD

**Issue by rong2er** [422658476/MPV-EASY-Player#66]

**Comment by 422658476** [comment]
如果刚开始用mpv，请先在mpv官方提交issue来解决这个问题（什么是svp，用来做什么的相信很多人都不知道），如果在mpv中能够启用这个，那么在mpv-easy player中，查看首页的说明，通常不需要调整，或者只需要少量调整就一样能启用。

**Comment by 422658476** [comment]
@rong2er  没有问题请关闭这个issue
