### ISSUE TITLE
能否将gpu-next增加到视频输出驱动设置的选择项中

### ISSUE THREAD

**Issue by iseku** [422658476/MPV-EASY-Player#69]
为了支持杜比视界播放，需要设置vo=gpu-next，当前版本的视频输出驱动选择项只有gpu和direct3d，如果手工改动rjno1.conf可以生效，但是如果使用设置功能更改其它设置保存后又会被覆盖成vo=gpu，也尝试直接修改mpv.conf没有作用。
另外说明中的增加额外配置[ini-custom]的方法，测试过也不起作用。

**Comment by 422658476** [comment]
使用ini-custom的方式添加是绝对有用的，如果没用可能和你修改过mpv.conf有关(请不要手动修改这个文件，这会导致程序不正常，这个文件中使用了3个警告提醒不能修改)，这需要你自行排查。
不会添加这个选项的原因，ini-custom是否会生效请参考这个issue:
https://github.com/422658476/MPV-EASY-Player/issues/51#issuecomment-1280029056
