### ISSUE TITLE
不能拖动字幕添加给正在播放视频,甚至不能拖动视频到播放窗口播放

### ISSUE THREAD

**Issue by helfee** [422658476/MPV-EASY-Player#7]
rt

**Comment by 422658476** [comment]
请勿使用拖放的方式添加外挂字幕，这样既没有效率，并且每次都要手动操作。
正确的方式是把外挂字幕和视频文件存放在同一路径下，并且命名成相同名字。
比如：
e:\软件No1.mkv
e:\软件No1.ass
这样当你每次双击播放这个mkv文件时，播放器就会自动加载这个外部的ass文件

**Comment by 422658476** [comment]
甚至不能拖动视频到播放窗口播放:
这个很有可能是因为你没有关闭windows的uac造成的，解决这个问题的办法：
进入mpv-easy设置界面-关闭uca，根据界面上的提示操作即可。

**Comment by helfee** [comment]
作者你好,
1 使用拖动方式添加字幕是因为在多个字幕文件寻找翻译准确的字幕,需要依次尝试,,如果来回改名有些不便,
2 不能拖放的情况用win10ltsc和ltsb2016都试过,如果当前用户是管理员则正常,其它用户就不行了,可能程序是用的管理员权限,资源管理器默认不是此权限,所以无法拖放;uac是关闭了的.
3 还有个问题,我用的是小米硬盘路由,电影文件是路由共享文件夹映射的共享盘 Z: ,和问题2相似,可能因为管理员权限问题,程序菜单打开文件对话框看不到共享盘

问题2和3都是因为程序默认使用管理员权限,如果可以不用高权限应该就没有这问题了

你的程序很好用,资源占用非常低,感谢,看到CPU资源占用零点几就舒坦 :)

**Comment by 422658476** [comment]
抱歉，这个问题关闭后我就一直没有看过，现在才发现有回复。
1、拖放方式添加字幕的问题。
太多人问这个问题，算了妥协，现在这个功能会被添加到下个版本中，你可以在下个星期在【MPV-EASY无边框GUI模式】中体验到它。注意事项请查看更新日志。
 :(
2、问题2和问题3请确认你是否现在真的在用windows的用户账户（标准账户），而不是像普通人一样使用的是自己用户名的administrator账户（管理员账户）。

如何确认：
当你真的在使用windows的用户账户（标准账户）时，当你运行mpv-easy player时：

情况1：用户账户并且开启uac。
双击运行mpv-easy player.exe时，会弹出提示框让你输入管理员账号的密码才能运行
运行后无法使用拖放打开视频文件
点击控制面板-用户账户-更改用户账户控制设置（也就是用来关闭uac）界面，会弹出提示框让你输入管理员账号的密码才能显示
情况2：用户账户并且uac已经被管理员账号关闭。
双击运行mpv-easy player.exe直接能运行（设置中：原生1运行模式），但会跳出提示框告诉你系统盘使用fat32格式，无法使用此模式运行（设置中：原生1运行模式）。
设置中：改为兼容模式运行后可以正常运行，可以使用拖放打开视频文件
点击控制面板-用户账户-更改用户账户控制设置（也就是用来关闭uac）界面会无效，也就是无法显示

也就是说，如果你的uac 真的已经按照步骤关闭，并且重启了系统，那么不管你使用的是管理员账户还是标准账户，你都可以使用拖放的方式打开视频文件。

高权限运行实际上并没有问题，就像情况2一样，如果你使用用户账户，在关闭uac的情况下程序只能强行使用用户权限运行，导致默认最好的原生1模式因为权限不够都无法使用。
所以还是建议你使用最常见的administrator账户并关闭uac后使用，现在你的问题可能是没有真正的关闭uac引起的，可能是关闭后没有重启系统。如果你真的使用用户账户运行，那么你遇到的情况会和我描述的一样多。

**Comment by helfee** [comment]
![TIM图片20190326171858](https://user-images.githubusercontent.com/4361294/55042545-e6c6f780-506c-11e9-8815-87ded5f877a0.png)

非常感谢~能拖放字幕方便多了
关于权限问题, uac向来是关闭的,账户类型等如图,我的用户是非admin帐号名但有admin权限..使用习惯应该不算特殊情况吧,不知您是否用win10测试过,看软件说明截图是win7,两个系统权限方面会不会有差异.

**Comment by helfee** [comment]
我又回复了,希望做的越来越好😀

banana <notifications@github.com> 于2019年3月26日周二 下午1:42写道：

**Comment by 422658476** [comment]
通过截图可以了解到你使用的是和普通人一样的自己用户名的administrator账户（管理员账户）。
这种情况下，关闭uac后是不会有任何拖放方面的问题的，也就是当你把一个文件拖放到播放器界面中时鼠标右侧会出现【+复制】字样。

如果你现在还是不能使用拖放，那么很有可能是系统方面的问题。

你的问题应该算是个例，并且这个问题和系统版本（windows 10还是windows 7）无关，因为拖放和uac的问题在2个系统上都是一样解决的，方式一致并且被测试过。

加上使用【打开文件...】看不到【网络位置】下映射的网络驱动器，那么系统有问题的概率就更大了，因为不管是不是管理员权限，网络位置应该是都能看到的。

解决方式：
这2个问题目前只能你自己排查。

1、使用右键管理员权限打开其他程序，比如firefox，同样使用firefox中的【打开文件...】功能检测是否同样看不到【网络位置】下映射的网络驱动器，以此来检测问题是否存在普遍性，拖放也是。

2、检测和拖放、映射网络驱动器有关的系统组策略是否被修改过。

3、检测映射网络驱动器有关的系统服务是否正常开启。

4、在其他人的电脑上测试是否有同样这2个问题。

5、如果你通过以上方式还是不能解决问题，或者有些方式你不能办到，那么保存好重要资料，通过重新安装系统来解决这个问题是最简单的，不管是重新安装windows 7旗舰版，还是windows 10专业版的稳定版都可以很好的解决，至于企业版，没有测试过，但应该也不会有问题。

目前我只能把这个issue重新打开，但是解决问题只能靠你自己，因为其他留言中遇到拖放问题的人通常只需要关闭uac就能解决。

如果你解决了这个问题，那么可以把解决方式分享出来。

**Comment by helfee** [comment]
https://blog.walterlv.com/post/start-process-with-lowered-uac-privileges.html
这篇文章有一段话

> 不过值得注意的是，Windows 7 上控制面板的 UAC 设置拉倒最低就是关掉 UAC 了；Windows 8 开始拉倒最底 UAC 还是打开的，只是不会提示 UAC 弹窗而已。也就是说，拉倒最底的话，Windows 7 的 UAC 就会关闭，explorer.exe 就会以管理员权限启动。

说明默认情况下win10即使关闭uac,系统的explorer及一般程序也是用的普通权限而非administrator,但咱们MPV-EASY Player是用的admin权限,资源管理器到播放器之间因为不是相同权限组 肯定是无法拖放了,播放器无法看到资源管理器映射的网络驱动器盘符也是因为这原因

解决思路有两个
一是播放器不要申请admin权限,使用标准用户权限
二是修改系统设置使所有程序都默认admin权限

思路二具体操作来自 https://www.zhihu.com/question/37157445/answer/70723177

> 本质上是Windows本地安全策略的限制，XP时代是没有的，Vista以后才有。我只说怎么改吧：**开始-运行-gpedit.msc，左侧树形图找到本地计算机策略->Windows设置->安全设置->本地策略->安全选项按名称排序，找到用户账户控制的配置：以管理员批准模式运行所有管理员：这个是题主你遇到的情况，明明是管理员，但默认行为不是管理员，把这个开关禁用**，你操作的行为就跟XP是一样的了（管理员的所有操作都以管理员权限运行）。另外，“管理员批准模式中管理员的提升权限提示”的行为也会影响一些。其实正常情况下，不应该使用管理员账户操作Windows，这是微软的本意，但很多软件设计的不够好，必须用管理员权限，所以微软在Vista以后加入UAC以及这个安全策略，所有涉及系统安全的动作都需要提权才行，其实就是把管理员给降级了，这也是没办法的事情，因为管理员账户被滥用了。

虽然这样做可以解决,但禁用后发现有些程序默认行为受影响了,不太习惯,又改回原来设置了..还是希望MPV-EASY Player做些调整,不要申请admin权限实现软件功能,这样对于某些用户( _我这样的:)_  )来说比较方便

**Comment by 422658476** [comment]
非常感谢，根据你的反馈，我终于想起来windows 10下彻底关闭uac光靠把用户账户权限控制界面的滑块拖动到最底部是不够的，之前这个功能一直没有在windows 10下测试并且之前关闭windows 10的uac我都是使用之前制作的彻底关闭uac小工具解决的，所以被忽略掉了。

请下载最新的0.29.1.17版，再次使用设置界面修改过的关闭uac功能解决关闭uac的问题。

至于降低程序运行权限的问题：关闭uac是一个一劳永逸的问题，只要关闭uac，那么所有和权限有关的问题在使用系统时都不会遇到，也不会老是跳出恼人的警告界面，人机交互会改善很多，当然也有我之前描述的那些，总之是带来的好处更多，所以程序运行权限并不会考虑降低，这点请谅解。

**Comment by helfee** [comment]
感谢~处理这么迅速👍

banana <notifications@github.com> 于2019年3月27日周三 下午11:51写道：
