### ISSUE TITLE
关于流媒体播放无法拖动进度，更改倍速等

### ISSUE THREAD

**Issue by Aurora-Simba** [422658476/MPV-EASY-Player#70]
在无边框GUI下，流媒体播放无法使用拖动进度，更改倍速等一系列操作，原生gui无上述问题

**Comment by 422658476** [comment]
流媒体通常很难获取，也就只有比如iptv，流媒体通常会不停加载，所以没有完整的进度，这也导致很难进行调试，加上根本不会使用，所以基本不进行测试，显然可能会遇到各种的问题。

如果你需要播放流媒体，并且遇到这些问题，那么请使用原生gui。
