### ISSUE TITLE
Option to disable autoplay for playlists and keybinds for changing video playing in playlist

### ISSUE THREAD

**Issue by HyperLemons** [422658476/MPV-EASY-Player#72]
Hello, thank you for creating such a wonderful GUI for MPV, it's by far the best I've found and used.

Is it possible to make an option to disable autoplay for playlists? Video players like MPC-HC and the default Windows 10 video player/image viewer doesn't automatically switch to the next video in a playlist.

[This issue](https://github.com/mpv-player/mpv/issues/4738) from the main MPV repository lists 2 options (supposedly) replicates this behavior:
keep-open=always
reset-on-next-file=pause

I've tried to add these 2 options to several different .ini and .conf files inside MPC-EASY but had no success.
If an option that would replicate this functionality I'm talking about or just simply toggle the 2 options I listed could be added to the settings it would be really great. :)

Also, there was comments on the issue mentioning some keybinds.
1 of them was a restart button for a file: https://github.com/mpv-player/mpv/issues/4738#issuecomment-321080148

The other was mentioning skipping to the next file in the playlist if the file playing was near/in the last chapter or previous file in the playlist if the file was near/in the first chapter.

If keybinds could be set to do those functions it would be wonderful.

I've also found the using the UP arrow does go forward to the next file in a playlist, but the DOWN arrow key does not go back to the previous file in a playlist. I have no idea if this is a bug or something conflicting.

**Comment by 422658476** [comment]
Why use a playlist if you don't want to automatically play the next file?
If there is no option for this function in the settings of mpv, that is, if it cannot be implemented in mpv, then this function will not appear in mpv-easy player, which is determined by mpv.
This function requires you to submit an issue to the mpv official, and let the contributor give you the correct answer (the corresponding setting should not be found in the mpv manual), and after implementing it in mpv, you can add the setting to the rjno1.conf file That's it.
If there is no setting, it can only be realized through lua script or js script. In theory, use the playback end signal provided by mpv to trigger a pause when the playback ends.

Shortcut key issue for replay. For this, you only need to add a shortcut key in input.conf, and jump to the time point of 00:00:00 after pressing it.

The playlist plays the previous file and the next file. I don’t know whether you are using the mpv’s built-in playlist or the advanced playlist. Usually, these common shortcut keys in the two playlists are normal. If you want to To modify the shortcut keys for these functions in the advanced playlist, just open and edit the corresponding shortcut key settings in playlistmanager.lua.
