### ISSUE TITLE
Export custom OSC

### ISSUE THREAD

**Issue by BlueIncog** [422658476/MPV-EASY-Player#74]
I have made a custom OSC in the MPV EASY Player app:
![image](https://github.com/422658476/MPV-EASY-Player/assets/53572359/339eada4-fea0-48da-b7c0-b1f2f295d1e2)
I would like to be able to access the .lua source files for the CUSTOM OSC that I made in the app, not the preset ones.
How would I do this?

**Comment by 422658476** [comment]
This is not a osc based lua.
The ui under mpv-easy borderless gui is based on qt, including the osc on the screenshot, which cannot be exported because the implementation method is completely different
