### ISSUE TITLE
Integrate uosc or mpv-quality-menu to choose stream quality

### ISSUE THREAD

**Issue by trimechee** [422658476/MPV-EASY-Player#75]
Hello, it will be great to integrate these UI to our beloved MPV-EASY-Player to choose the video stream quality please :  standard quality ou HD quality, i tried with basic mpv player but it is very difficult form me to install these UI....thank you !

https://github.com/tomasklaen/uosc
https://github.com/natural-harmonia-gropius/mpv-config
https://github.com/christoph-heinrich/mpv-quality-menu

**Comment by 422658476** [comment]
If you want to add and try this function, please switch to mpv native gui, and follow the instructions of these functions to add them to the corresponding folder and text to achieve it. The corresponding directory of mpv-easy player has also been given . mpv-easy player is completely designed for local video files, and will not consider and debug the problem of playing online videos.

**Comment by trimechee** [comment]
We undestand, thank you :) we can't put yt-dlp in the directory of MPV-EASY-Player  ?

**Comment by 422658476** [comment]
mpv-easy player follows the principle of mpv: only give the most basic things, and use scripts and other extra things to enhance the player according to the user's personalized requirements, so as to take into account performance and functions, and avoid bloat and complexity. What you said needs to be added by yourself, these are not necessary and commonly used functions.

**Comment by trimechee** [comment]
Interesting ! Thank you :)
