### ISSUE TITLE
硬解模式选项有误

### ISSUE THREAD

**Issue by hzyzr88** [422658476/MPV-EASY-Player#76]
![1](https://github.com/422658476/MPV-EASY-Player/assets/147784324/88ccb3d7-a440-4fe1-8f0d-557fc9cd5878)
此处应为d3d11va文本描述有误 且无法正常启用
![2](https://github.com/422658476/MPV-EASY-Player/assets/147784324/c495d9fd-86c4-4021-ae5b-882cf99a44a8)

**Comment by 422658476** [comment]
感谢指正，下个版本会修复
