### ISSUE TITLE
窗口最大尺寸

### ISSUE THREAD

**Issue by hzyzr88** [422658476/MPV-EASY-Player#77]
在使用 MPV-EASY无边框GUI时 设置初始窗口最大尺寸百分比后 有下列情况
       1. 通过默认程序打开视频（双击文件直接通过关联程序打开）都可以正常执行，而通过打开程序直接拖拽或菜单打开将不执行（以窗口左上角为定点直接以视频像素直接绘制窗口大小，若视频像素大于桌面会按照最大桌面像素绘制）。 若在已经打开视频的基础上再次打开其他不同分辨率视频也会出现上述情况，而打开相同分辨率视频将会保持原有窗口大小。
       2. 在使用播放列表播放多个视频时，若视频分辨率不一致窗口大小会直接改变并且不遵循最大尺寸百分百（以窗口左上角为定点直接视频像素直接绘制窗口大小，若视频分辨率大于桌面会按照最大桌面像素绘制），若分辨率一致将保持原有窗口大小。

使用原生GUI不会出现上述情况，所有打开的方式 窗口都将执行窗口最大尺寸百分比。
使用环境为 win10 19044.1620 MPV运行模式为原生3

最后感谢作者的付出，希望软件越来越好

**Comment by 422658476** [comment]
这2个不是bug，设置中写的也是初始化时窗口尺寸大小，也就是第一次运行时的窗口大小，不包括显示后的二次添加播放，这也是为了避免众口难调的复杂的窗口调整逻辑。当使用拖放时已经是第二次了。播放列表也是，自动默认添加的连续剧都是同一分辨率，如果不同就会调整为原始尺寸，这也是为了防止各种黑边，夹杂竖屏视频时画面变得太小的问题，这些不管怎么自动最后都是需要手动调整的
