### ISSUE TITLE
希望新增一个osc样式以及支持进度条缩略图预览

### ISSUE THREAD

**Issue by daochenmeng** [422658476/MPV-EASY-Player#78]
osc样式地址 https://github.com/FinnRaze/mpv-osc-modern-f
缩略图预览 https://github.com/po5/thumbfast

**Comment by 422658476** [comment]
如果你能在mpv下实现这个，那么在mpv原生gui下也能自己手动实现。mpv-easy无边框gui下有类似的osc，因为osc实现的方式不同以及性能方面的考量，不会添加缩略图这个功能
