### ISSUE TITLE
osd-bar插件受配置参数fs=yes影响未显示问题

### ISSUE THREAD

**Issue by hero-z1** [422658476/MPV-EASY-Player#79]
我下载使用版本是mpv-x86_64-20231112-git-7cab30c
用的插件[osd-bar](https://github.com/422658476/MPV-EASY-Player/blob/master/portable-data/scripts/osd-bar.lua)
当我配置了fs=yes时，退出全屏后不显示进度条。如果取消fs参数，插件工作正常，手动进入全屏消失，退出全屏后显示。
这个小问题如何解决呢？

**Comment by 422658476** [comment]
@hero-z1 
感谢反馈，这个是脚本中的非常严重的bug，甚至会导致mpv崩溃。
请从目录中下载已经修改过的osd-bar.lua，就可以解决这个问题。
万分感谢。
