### ISSUE TITLE
Error at start

### ISSUE THREAD

**Issue by 70V07** [422658476/MPV-EASY-Player#84]
downloaded from Scoop package manager

```
scoop bucket add extras
scoop install extras/mpv-easy-player
```

when I start in Windows 11 Pro the app 

![Screenshot 2024-02-06 094909](https://github.com/422658476/MPV-EASY-Player/assets/46967291/fdf1c1d0-8092-42bb-9ea1-56c7cc5515be)

**Comment by 422658476** [comment]
Please download and install it directly from github. It has been tested on Windows 11 and can run normally.
