### ISSUE TITLE
Blurred icons at high resolution

### ISSUE THREAD

**Issue by DeadFlamingo** [422658476/MPV-EASY-Player#86]
3840x2160 on 150 scale all icons are very blurry
![image](https://github.com/422658476/MPV-EASY-Player/assets/43293830/fabbc23a-b793-4a94-9dcd-64f46da41574)

This is how it looks
![image](https://github.com/422658476/MPV-EASY-Player/assets/43293830/806e4e07-9ef2-4ced-a199-b29ac5e9159f)

is it possible to use a font instead of bitmap images?

**Comment by 422658476** [comment]
Although scaling is supported at the program level, the high-resolution display and non-default scaling are not tested too much, so the icons and text may be smaller. Some displays on the interface may also be abnormal.
