### ISSUE TITLE
打开MPV-EASY Player.exe提示无法运行。

### ISSUE THREAD

**Issue by lzxjimmy** [422658476/MPV-EASY-Player#87]
无法运行
错误原因：
请先运行MPV-EASY Player.exe一次，从而生成所有配置文件，并确保此程序和MPV-EASY Player.exe在同一路径下。
![20240412154958](https://github.com/422658476/MPV-EASY-Player/assets/52943841/ff31d3bf-4131-42aa-a21f-721f2fc28dc4)

**Comment by 422658476** [comment]
请运行一次MPV-EASY Player.exe，从而生成【data】文件夹以及其中的所有配置文件再运行其他3个mpv****.exe.
