### ISSUE TITLE
I made the source part in English.

### ISSUE THREAD

**Issue by DogancanYr** [422658476/MPV-EASY-Player#88]
Does it work like that?
It's easier to translate into other languages.
[(Source)en-mpveasygui.ts.txt](https://github.com/422658476/MPV-EASY-Player/files/15254728/Source.en-mpveasygui.ts.txt)

**Comment by 422658476** [comment]
Please don't do this, please use qt linguist for translation, changing it to txt will complicate simple and intuitive things.

**Comment by DogancanYr** [comment]
> Please don't do this, please use qt linguist for translation, changing it to txt will complicate simple and intuitive things.

I know it just needs to be in txt file format to be uploaded here, just delete the txt at the end.
It's also easier to translate from English to other languages and some software won't change it because other files already have the translation parts filled in. Does my edited file work?
[(Source)en-mpveasygui.zip](https://github.com/422658476/MPV-EASY-Player/files/15260938/Source.en-mpveasygui.zip)

**Comment by 422658476** [comment]
Please do not do this. This file is not used according to your thinking. If you have not used Qt translation software, please do not modify it.

**Comment by DogancanYr** [comment]
I didn't modify it, I replaced the translation part with the original. Because It is difficult to translate from Chinese to any other language. I set it to English as the original language.

**Comment by DogancanYr** [comment]
Can you please check if the software reads it correctly?
Because there are repetitive sentences in the translation from Chinese to English, I removed those sentences.

**Comment by 422658476** [comment]
This file is not used according to your thinking. If you have not used Qt translation software, please do not modify it.

**Comment by DogancanYr** [comment]
Ok...

**Comment by 422658476** [comment]
If you know how to use qt linguist, then there will only be some problems that you don't know how to translate.
You can complete all the translation work on your own computer, and the various questions you asked will not appear. By replacing the two qm files finally obtained with the two English qm files, you can directly see what the translated software interface looks like. None of this needs to go through me, it can be done by one person independently. If you don't know how to operate, please do not edit these language files.

**Comment by DogancanYr** [comment]
Thanks. Now I'm translating according to the original file . I just thought it could be better if it turned out that way.

**Comment by 422658476** [comment]
If you really want to translate the entire software language interface, you must use Qt Linguist for translation work, otherwise there will be many problems besides translation, and even translation may cause formatting errors, because the translation of the setting interface has hundreds of lines. Please don't translate in source code. If you have completed the translation, you only need to provide me with 2 files with the [ts] suffix.

**Comment by DogancanYr** [comment]
I have completed 90% of the Turkish translation.
Can you at least make sure it's fully functional?
[Translation.zip](https://github.com/422658476/MPV-EASY-Player/files/15267502/Translation.zip)

**Comment by 422658476** [comment]
It works fine and you can continue translating until it's complete。

**Comment by DogancanYr** [comment]
[Translation.zip](https://github.com/422658476/MPV-EASY-Player/files/15278682/Translation.zip)

**Comment by 422658476** [comment]
Any documents you translate will not be accepted, and you should know why.

**Comment by DogancanYr** [comment]
Qt linquist does not translate lines with a # sign at the beginning. When I do it with another program, it moves the lines to the end.

**Comment by DogancanYr** [comment]
It's working, what do you still want?
[language.zip](https://github.com/422658476/MPV-EASY-Player/files/15283667/language.zip)
