### ISSUE TITLE
msg-level=all=warn会导致启动时闪退

### ISSUE THREAD

**Issue by tonysky2002** [422658476/MPV-EASY-Player#89]
rjno1.conf配置文件中加入msg-level=all=warn后会导致程序闪退. 改成msg-level=all=info正常.

**Comment by 422658476** [comment]
如果需要使用msg-level=all=warn，那么请在添加前在设置界面切换到【mpv原生gui】，或者直接使用mpv。
使用【mpv-easy无边框gui】时，请勿添加这条参数。gui程序需要使用mpv在日志管道中输出的日志信息提取必要数据来帮助界面在启动时更快的显示出来。当你更改日志层级后，日志输出的内容和格式会完全改变，导致数据无法获得，界面会因此隐藏而不显示出来。
