### ISSUE TITLE
MPV-Easy Requires Admin Privileges

### ISSUE THREAD

**Issue by Sorin-M-Oprea** [422658476/MPV-EASY-Player#9]
MPV-Easy starts by default with admin request. This is not proper way as it can become annoying.

UAC should NOT be disabled as it offers certain protection levels in the Windows OS.

This is a wonderful piece of software. and I kindly ask you to make modifications to MPV-Easy and make it run with no admin privileges.

**Comment by 422658476** [comment]
After a long time, I have found a way to improve this problem, which will be added in the next version. Thank you very much for submitting the problem.
