### ISSUE TITLE
高分屏使用时遇到的问题

### ISSUE THREAD

**Issue by jordan-msftfan** [422658476/MPV-EASY-Player#90]
![Snipaste_2024-05-26_19-07-58](https://github.com/422658476/MPV-EASY-Player/assets/77601580/3c7f827f-e4be-4f37-b19d-991e75484ef0)
![Snipaste_2024-05-26_19-08-31](https://github.com/422658476/MPV-EASY-Player/assets/77601580/7488d21f-a324-4109-91f4-c7b669d5fa60)
![Snipaste_2024-05-26_19-10-36](https://github.com/422658476/MPV-EASY-Player/assets/77601580/223e470e-e0a6-4e13-a2a9-3038bca42cab)

4K 200% 的情况下，字体过小，和没有缩放一样，图标未以矢量图的方式缩放，而是1:2点对点缩放

**Comment by 422658476** [comment]
这个无法解决，程序已经尽可能兼容缩放，但缺少4k显示器，无法进行这种情况下的测试和调整。
你只能尝试注销系统或者重启系统一次，检测字体是否自动变大。测试时需要注销一次后字体会自动变大，但实际使用4k显示器时效果未知。

**Comment by jordan-msftfan** [comment]
![Snipaste_2024-05-27_13-56-32](https://github.com/422658476/MPV-EASY-Player/assets/77601580/e4ab35ee-7072-4155-b33a-eca1e8a51866)
![Snipaste_2024-05-27_13-58-06](https://github.com/422658476/MPV-EASY-Player/assets/77601580/9eb1e98b-1685-40ba-858f-64671f3a1c86)
在注销重进之后，字体缩放正常，虽然很遗憾矢量图标未能很好利用缩放后的次像素，但至少可用了，除非盯着屏幕不然也没啥太大的瑕疵。
