### ISSUE TITLE
A bug when using lastest mpv version 

### ISSUE THREAD

**Issue by Rickyrvxlovet** [422658476/MPV-EASY-Player#92]
Hi there,
I'm using the latest version of mpv and I've noticed that the OSD back color is missing. Could you please let me know how I can fix this?
Thanks in advance!

**Comment by 422658476** [comment]
I have confirmed this problem and found a solution. It will be fixed in the next version. Thank you for your feedback.

**Comment by 422658476** [comment]
You can try to fix this yourself.
Just edit rjno1.conf

delete   osd-shadow-color=1.0/1.0/1.0/0.22

Modify value
osd-shadow-offset=5

add
osd-border-style=background-box
