### ISSUE TITLE
您好， 我需要修改screenshot 中默认截图保存的文件名， 

### ISSUE THREAD

**Issue by irx999** [422658476/MPV-EASY-Player#97]
能带上 当前播放的文件名+当前播放的时间戳，以便我 能准确的定位该截图出现在视频中的准确位置

**Comment by 422658476** [comment]
请查看mpv的手册，截图路径，文件名格式，文件名内容，或者其他都可以改成你想要的.
请填写到rjno1.conf中。

https://mpv.io/manual/stable/#options-screenshot-format

**Comment by irx999** [comment]
非常感谢您的及时回复， 我已正确配置好我需要的功能。
